### ISSUE TITLE
Scheduled Workflow Fails to Complete

### ISSUE THREAD

**Issue by ChestoOfGlen** [Shuffle/Shuffle#1005]
**Describe the bug**
Workflow with a subflow hangs and does not complete when executed on a schedule, clogging up the Orborus server with worker containers.
Same workflow completes fine when executed manually.

**To Reproduce**
Create a workflow similar to this one. Have it execute on a schedule. Scheduled runs never complete and hang.
Condition prior to TheHive app is checking that a threat score is present so that empty cases don't get created for us.
![image](https://user-images.githubusercontent.com/37160206/207997860-d4e6c400-44cf-49a9-8e0f-6c05d6d476c3.png)

**Expected behavior**
That the workflow should complete properly when executed by the schedule.

**Screenshots**
Hanging workers
![image](https://user-images.githubusercontent.com/37160206/207998095-7877d28c-10d3-4be6-ae85-1eba9874b2ca.png)

Workflow execution both by schedule (fails to complete) and manual (completes properly).
I am not sure what the difference is between the manual execution and the scheduler, but the scheduled execution ends up with two extra steps being reported in the subflow.
These workflows were running fine prior to me upgrading our instance to v1.1.0.
![image](https://user-images.githubusercontent.com/37160206/207998173-f1dc0a27-4cb8-4b9b-89e3-9d0aae7166a3.png)

**Comment by frikky** [comment]
Hey there! Are you sure it actually fails to complete? I'm thinking this may be a visual bug, or a case of randomness affecting whether it finishes properly or not (seeing as it says 8/6, which shouldn't be possible)

Could you try to run it multiple times manually and verify that it works every time? 

Thanks

**Comment by ChestoOfGlen** [comment]
It's less whether or not it fails to complete, the main issue is that the workers do not get cleaned up and start clogging up the max executions queue while saying they've got 8 results for 6 actions and "continuing X app as all parents are NOT done".

From the testing I did while fixing this issue (in our production instance) it looks like the scheduled runs do not like having the condition on the first branch of the sub-flow. I tried with both a regex and a contains with the same end result.
This was working fine for us while running on 1.0.5, and only started having problems for us once I upgraded to 1.1.0.

In the end, I rebuilt this workflow to do the filtering before sending to the subflow and that has resolved this issue with the hanging workers for this one.
![image](https://user-images.githubusercontent.com/37160206/208345771-d6d6733b-5db4-42ac-9e45-fe116cbefbb2.png)

**Comment by ChestoOfGlen** [comment]
Related to having workflows show more completions than there are actions to do, we do have another workflow that periodically does this too, but not to such a level that it clogs up the entire environment. 
I don't recall see it do this prior to upgrading from 1.0.5 to 1.1.0 but as this one "just works" I haven't spent too much time in it looking at the execution logs.
![image](https://user-images.githubusercontent.com/37160206/208347095-6adad832-2902-4f0b-ba60-d04b184ca2e9.png)


This happens to be the worst case I've seen, 43/24, as normally it's completing fine with 24/24 or with 25/24.
![image](https://user-images.githubusercontent.com/37160206/208346447-608a5f1d-272d-4060-ba43-9d374c47bd95.png)
![image](https://user-images.githubusercontent.com/37160206/208346592-40c463be-ed60-4066-9d01-9c14097befc9.png)

For this one (43/24 actions) there is currently 3 workers spun up for the same execution (at 5 minute intervals). Their logs all report exactly the same thing (the above log entries just repeated).
![image](https://user-images.githubusercontent.com/37160206/208346722-32bae5cc-5d3c-458f-8e09-afe0cc4d5483.png)

Let me know if you want anything more.
I have taken an export of our backend logs from around this time as well if needed. I just don't have the time right now to go through and sanitise them.

**Comment by frikky** [comment]
Hey! Please update your worker, and this should be sorted. There was an issue in the counter, making it jump way too far in cases where multiple apps start at once.

**Comment by ChestoOfGlen** [comment]
Thanks for the update Frikky.
I've updated the worker image (docker pull ghcr.io/shuffle/shuffle-worker:latest) and I'll keep an eye on things over the next week or so.

**Comment by frikky** [comment]
> Thanks for the update Frikky. I've updated the worker image (docker pull ghcr.io/shuffle/shuffle-worker:latest) and I'll keep an eye on things over the next week or so.

Heyo! Got any update? Does it work? :)

**Comment by ChestoOfGlen** [comment]
Hey Frikky, I am still seeing a handful of executions returning more actions than they have apps, but it isn't causing noticeable problems for us currently.
I've been pulled onto other projects internally, so I haven't been keeping a close eye on Shuffle performance except that it isn't triggering any of our high CPU % or load alerts, and our SOC aren't complaining to me about any slowdowns or breakages.

![image](https://user-images.githubusercontent.com/37160206/224213708-3af2d18d-730c-4ebe-a574-5cf98bae3e93.png)

**Comment by frikky** [comment]
> Hey Frikky, I am still seeing a handful of executions returning more actions than they have apps, but it isn't causing noticeable problems for us currently.
> I've been pulled onto other projects internally, so I haven't been keeping a close eye on Shuffle performance except that it isn't triggering any of our high CPU % or load alerts, and our SOC aren't complaining to me about any slowdowns or breakages.
> 
> ![image](https://user-images.githubusercontent.com/37160206/224213708-3af2d18d-730c-4ebe-a574-5cf98bae3e93.png)
> 

Nice that it's working at least. Could you show the nodes that may be triggering twice, and are the workflows finishing in a timely manner? Look for results with the same name 😊

**Comment by frikky** [comment]
@ChestoOfGlen bump :)

**Comment by frikky** [comment]
So this has to be a cache thing then. We'll release minor update 1.1.5 over the weekend which should have this solved :)
