### ISSUE TITLE
Shuffle File Upload - FAILED GETTING FILE. IS IT DELETED error

### ISSUE THREAD

**Issue by denizciftci-sec** [Shuffle/Shuffle#1009]
Hi, I try to upload few files from exchange as attachment. I see the files under Files menu but when I try to download them, got this error AILED GETTING FILE. IS IT DELETED. In backend server, the file sizes are 0.
And having these errors in backend server.

2023/01/04 18:31:46 [INFO] Created file /shuffle-files/89efbee1-1f36-4be1-8a87-1bd953c76097/3fdf33c1-862d-4cd2-a0b3-b98763adf2a4/file_4d0f736d-0e0a-41c9-955d-c417f920e5b6 with namespace ""
2023/01/04 18:31:46 [WARNING] No users found for apikey 89f6a9d0-e57c-4ef6-82dc-87a837ff7c0a
2023/01/04 18:31:46 [WARNING] Apikey Bearer 89f6a9d0-e57c-4ef6-82dc-87a837ff7c0a doesn't exist: No users found for this apikey
2023/01/04 18:31:46 INITIAL Api authentication failed in file upload: No users found for this apikey
2023/01/04 18:31:46 [INFO] Authorization is correct for execution 8b36f7e5-9066-4e8e-839c-d953a0ef9680!
2023/01/04 18:31:46 [INFO] Should UPLOAD file file_4d0f736d-0e0a-41c9-955d-c417f920e5b6 if user has access
2023/01/04 18:31:46 [INFO] STATUS: created
2023/01/04 18:31:46 [WARNING] Failed hashing in encrypt: No encryption modifier set. Define SHUFFLE_ENCRYPTION_MODIFIER and NEVER change it to start encrypting auth.
2023/01/04 18:31:46 [ERROR] Failed encrypting file to be stored correctly: No encryption modifier set. Define SHUFFLE_ENCRYPTION_MODIFIER and NEVER change it to start encrypting auth

**Comment by frikky** [comment]
Hey there!

I'm guessing this has to do with access rights on the file location. Could you send permissions for the file folder please?

```
ls -alh
```

**Comment by denizciftci-sec** [comment]
Hi @frikky,

When I updated the version of docker images, the problem was fixed.
Thanks.

**Comment by frikky** [comment]
Nice! Glad the last version fixed it 😊

**Comment by denizciftci-sec** [comment]
Hi @frikky , Could you please assist me regarding https://github.com/Shuffle/Shuffle/issues/1011

**Comment by frikky** [comment]
> Hi @frikky , Could you please assist me regarding #1011

Hey! Could you add a screenshot of the problem you're facing, and add info about your Shuffle version version (nightly, latest, 1.1.0)?
