### ISSUE TITLE
Shuffle Internet Access Through Proxy Issue - Lower Case Letters

### ISSUE THREAD

**Issue by denizciftci-sec** [Shuffle/Shuffle#1011]
Hi,

Based on documentation, I configured backend and orborus with proxy settings (we are using docker-compose environment)
Currently, backend and orborus configured with **http_proxy** / **https_proxy** and able to access internet via container cli - but I am not able to access internet via shuffle APPS (for simplicity tested http app with curl www.google.com > connection refused).
Based on official documentation, letters should be **uppercase** letters, but i can confirm that it does only work with **lowercase** letters. 

How can I fix this proxy issue, any advise?

.env variable of back-end
http_proxy=http://192.168.38.10:3128
https_proxy=http://192.168.38.10:3128
no_proxy=127.0.0.1,.localhost,10.96.3.76,thehive,cortex,misp
NO_PROXY=127.0.0.1,.localhost,10.96.3.76,thehive,cortex,misp
SHUFFLE_PASS_WORKER_PROXY=TRUE
SHUFFLE_PASS_APP_PROXY=TRUE

**Comment by denizciftci-sec** [comment]
figured out. typed incorrect env parameters.

**Comment by frikky** [comment]
> figured out. typed incorrect env parameters.

Phew, glad that's not a worry. Proxy hell \o/
