### ISSUE TITLE
Bug in the code checking the conditions

### ISSUE THREAD

**Issue by tristandostaler** [Shuffle/Shuffle#1020]
The code is essentially:
```
# pseudocode
for something:
    if check:
        continue
        return # This will never be executed
```

The return instruction here will never be executed because of the continue preceeding it.

See: https://github.com/Shuffle/Shuffle/blob/f474cbe8460f9407955511a24f286018153bedae/backend/app_sdk/app_base.py#L2800-L2801

**Comment by frikky** [comment]
Thanks! These are from when we changed rules from ALL branches must 100% work to One branch must 100% work. Removed the parts that are not being reached.
