### ISSUE TITLE
Other bug in the code checking the conditions

### ISSUE THREAD

**Issue by tristandostaler** [Shuffle/Shuffle#1021]
The code is essentially:

```
# pseudocode
def function():
    doSomething()
    return False
    return True # This will never be executed
```
The last return instruction here will never be executed because of the return preceeding it.

See: https://github.com/Shuffle/Shuffle/blob/f474cbe8460f9407955511a24f286018153bedae/backend/app_sdk/app_base.py#L2851-L2855

**Comment by frikky** [comment]
#1020 and #1021 fixed in sdk!
