### ISSUE TITLE
Workflows never complete due to lack of shuffle-worker image.

### ISSUE THREAD

**Issue by jmolletAMNH** [Shuffle/Shuffle#1097]
**Describe the bug**
Workflows fail to complete because shuffle-orborus fails to create worker containers due to a failure to pull the latest image of shuffle-worker.

**Expected behavior**
I expect the shuffle-orborus container to generate worker containers to complete workflows.

**Screenshots**
![image](https://user-images.githubusercontent.com/103048713/233657366-7a829afa-abcf-435a-bfcb-9ca7c04030c6.png)

**Debug logs**
shuffle-orborus  | 2023/04/21 08:15:02 [ERROR] Container create error: Error response from daemon: No such image: ghcr.io/shuffle/shuffle-worker:latest
shuffle-orborus  | 2023/04/21 08:15:02 [WARNING] Execution ID d52d4e2a-76a5-4914-890a-96497a80a9be failed to deploy: Error response from daemon: No such image: ghcr.io/shuffle/shuffle-worker:latest

The only solution we have found at the moment is to bring down the compose service, manually pull the latest image and bring it back up. We have tried specifying version 1.1.4 in the configuration file but this did not resolve the issue.

**Comment by liam-star-black-master** [comment]
docker tag ghcr.io/frikky/shuffle-worker:1.1.5 ghcr.io/frikky/shuffle-worker:1.1.4 - this solved the problem for me

**Comment by jmolletAMNH** [comment]
The above answer by [liam-star-black-master](https://github.com/liam-star-black-master) did not end up panning out but after manually pulling the image down the problem went away.

Just did a clean reinstall of Shuffle last week and I am now running into this issue again. Specifying `SHUFFLE_WORKER_VERSION=latest` in the .env file is my current attempt at a solution.

**Comment by frikky** [comment]
> The above answer by [liam-star-black-master](https://github.com/liam-star-black-master) did not end up panning out but after manually pulling the image down the problem went away.
> 
> Just did a clean reinstall of Shuffle last week and I am now running into this issue again. Specifying `SHUFFLE_WORKER_VERSION=latest` in the .env file is my current attempt at a solution.

Hey, can you show a picture of the `/admin?tab=environments` page?  It is most likely a backed up queue with >100 queued jobs waiting.

**Comment by jmolletAMNH** [comment]
Hello @frikky here is the screenshot.

![image](https://github.com/user-attachments/assets/e5aacd7c-9745-4c6e-a2e6-38363092d5ee)

**Comment by frikky** [comment]
> Hello @frikky here is the screenshot.
> 
> ![image](https://private-user-images.githubusercontent.com/103048713/381968728-e5aacd7c-9745-4c6e-a2e6-38363092d5ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODcxNzAsIm5iZiI6MTczMDM4Njg3MCwicGF0aCI6Ii8xMDMwNDg3MTMvMzgxOTY4NzI4LWU1YWFjZDdjLTk3NDUtNGM2ZS1hMmU2LTM4MzYzMDkyZDVlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNTAxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmQwMWQ0OTg3MjEyNWI3NzIzZWRkZjg5NTg5MzE5NWJhMWJjYjUzNmZlOTI5MGNjMzQ1OTgzODVjN2EyZmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kisKXXzDrbsagID9Lg1jCBiKkpBoKNEKQeT0Es7i95c)

Gotcha - the queue looks backed up, and it says not running, so I'm not sure how to interpret that.

Could you try with the Scaling Shuffle docs I sent? That is more than fast enough to scale for pretty much anything

**Comment by frikky** [comment]
Bump @jmolletAMNH :)

**Comment by jmolletAMNH** [comment]
Hey @frikky, thank you for the answer. I will be testing this out later today and will let you know what the result is.
