### ISSUE TITLE
New Shuffle install - workflow changes are not saved and are lost on reload

### ISSUE THREAD

**Issue by HunterMorrell** [Shuffle/Shuffle#1099]
**Describe the bug**
I was having some issues with my existing Shuffle install and decided to try out a completely fresh version. I brought down the old version, cloned the repo into a new directory, and brought it back up. I followed the instructions in the install guide as well. 

After a fresh install, creating a workflow will make the workflow successfully, but then when making any changes to it (adding nodes, changing node info, etc) and then clicking the Save button does not seem to actually save the changes. Clicking the Save button and then execute will run the default "Change Me" node that the workflows are all created with, no matter what is currently showing in the workflow. Exiting out of the workflow or refreshing the page will clear out any changes and revert the workflow back to the default "Change Me" node.

Also, sometimes when creating a new workflow, the left app sidebar will just load and load. Refreshing does not fix this.

** Debug logs (NOT APPLICABLE FOR CLOUD)**
[shuffle_logs.txt](https://github.com/Shuffle/Shuffle/files/11387671/shuffle_logs.txt)

```

**Comment by frikky** [comment]
Hey,

based on the logs it looks like there's a problem connecting from the frontend -> backend somehow. This may be a database storage issue. Could you export logs for just the `shuffle-backend` container?

**Comment by HunterMorrell** [comment]
[shuffle_backend_logs.txt](https://github.com/Shuffle/Shuffle/files/11399689/shuffle_backend_logs.txt)

Here's the dump of backend logs. I did compress parts of it to cut down on the sheer amount there, which was basically the repetitive workflow clean up logs that run every few minutes and is pretty much exactly the same. In each instance, I kept the beginning and end set of logs intact to keep the flow of time clear, and just cut out the middle consecutive sets.

What's interesting is that it's still capable of successfully running existing workflows, as there was a scheduled workflow that ran and completed this morning at 5AM (9AM UTC in the logs).

**Comment by frikky** [comment]
> As an update, I came back to it today and it's apparently working now?? I have no idea what happened because it certainly wasn't working correctly when I walked away from it yesterday afternoon. I was able to login and create and update workflows in both the pre-existing instance and the new one.

I'm a bit perplexed, but think it definitely has to do with Opensearch. Please try to gather the logs immediately as you see it again, both from Backend and Opensearch :+1:

**Comment by frikky** [comment]
Closing due to no progreess
