### ISSUE TITLE
shuffle tools python fails to load JSON

### ISSUE THREAD

**Issue by tbi88** [Shuffle/Shuffle#1115]
Hi

I am using some python script to load some JSON from a previous node. This fails with the error.

"exception: Invalid \escape: line 1 column 8217 (char 8216)"

The funny thing is, that if I copy the JSON and do it manually on my machine or even in the "frikky/shuffle:shuffle-tools_1.2.0" image, it works as expected. Therefore there seems to be a special way how variables are inserted into the code.

Code starts with:

```
import json
hosts = json.loads(r'$fetch-host-details.#.body', strict=False)
```

I just updated the shuffle-tools image, but the issue is the same. 

It works by doing it manually like this:

```
docker run -it --entrypoint=/bin/sh -it frikky/shuffle:shuffle-tools_1.2.0
python
import json
text = r'<some very long json string>'
hosts = json.loads(text, strict=False)
```

Any idea how to work around on that?

Regards

**Comment by frikky** [comment]
> Hi
> 
> I am using some python script to load some JSON from a previous node. This fails with the error.
> 
> "exception: Invalid \escape: line 1 column 8217 (char 8216)"
> 
> The funny thing is, that if I copy the JSON and do it manually on my machine or even in the "frikky/shuffle:shuffle-tools_1.2.0" image, it works as expected. Therefore there seems to be a special way how variables are inserted into the code.
> 
> Code starts with:
> 
> ```
> import json
> hosts = json.loads(r'$fetch-host-details.#.body', strict=False)
> ```
> 
> I just updated the shuffle-tools image, but the issue is the same.
> 
> It works by doing it manually like this:
> 
> ```
> docker run -it --entrypoint=/bin/sh -it frikky/shuffle:shuffle-tools_1.2.0
> python
> import json
> text = r'<some very long json string>'
> hosts = json.loads(text, strict=False)
> ```
> 
> Any idea how to work around on that?
> 
> Regards

Hiya! 

How does the JSON string actually look, and does it render in the code editor as you would expect?
This may also be due to python3.11 being used, which we rolled back to 3.10. Could you check what python version is inside your docker tools?

**Comment by tbi88** [comment]
Hi frikky

Yes the JSON looks fine in the editor. I am already using python 3.10.

```
docker run -it --entrypoint=/bin/sh -it frikky/shuffle:shuffle-tools_1.2.0
/app # python -V
Python 3.10.0
```

Regards
