### ISSUE TITLE
Image propagation not working in Worker swarm network

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1126]
Worker image and App images are not being properly propagated to all servers required. This is because each server is not properly downloading the apps they may need during startup.

How to solve this properly? 
- Should the worker(s) periodically check for images that are used on the backend? 
- Should it automatically scale down to only the servers that have the image?

**Comment by 0x0elliot** [comment]
This seems like a false alert due to client's network misconfiguration.

> now here is my theory: they didn't unblock the right ports for docker swarm, like we saw, and thus image propagation couldn't happen to begin with. Shuffle should fail once and take care of it in the next run under the hood.

**Comment by 0x0elliot** [comment]
As long as it is verified by the client, I will close the issue.

**Comment by 0x0elliot** [comment]
worker PR: https://github.com/Shuffle/shaffuru/pull/187

**Comment by 0x0elliot** [comment]
backend PR: https://github.com/Shuffle/Shuffle/pull/1168

**Comment by frikky** [comment]
Had a VMWare problem, and image propagation is done~

Should try it on 3-5 nodes before knowing it works.

**Comment by 0x0elliot** [comment]
done. ready to close.

**Comment by frikky** [comment]
\o/
