### ISSUE TITLE
Docker swarm I/O timeouts when running on multiple machines

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1129]
This hasn't been replicated, but in certain cases every other request was timed out when running requests within the Shuffle Swarm network. In the below sample, connections fail to machine 2, when connecting to the VPC for a swarm service. 

Tests:
- Curl/wget from Orborus to Worker and see if all requests work.

**Sample network (2)**
Machine 1:
- Memcached
- Shuffle frontend, backend, orborus, opensearch
- Workers & Apps

Machine 2:
- Workers & Apps

**Comment by 0x0elliot** [comment]
in Scaling Shuffle with Swarm

- [ ] BASE_URL -> clarify as it being the public IP address, not the internal docker.
- [ ] Add diagrams and specify the swarm architecture. Specify machine wise where to use which command.

**Comment by 0x0elliot** [comment]
https://github.com/Shuffle/Shuffle/pull/1146

still has to be tested in a new environment.

**Comment by 0x0elliot** [comment]
let's close this max by today end.
