### ISSUE TITLE
Fix enter button click for search engine

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1136]
When searching in Algolia, make it possible to click enter. Right now, this just closes down the search engine.

Also on /search, make it search in all the search engines at once with a single piece of text (like the top bar)

**Comment by frikky** [comment]
Enter click should end up in a location like this: https://shuffler.io/search?q=query%20here

**Comment by ayush0033** [comment]
which query i need to use for navigate to particular Page? like after **/search?query="?"** cause there is no particular page where any query can run and show any result.

**Comment by ayush0033** [comment]
btw enter key is working fine and navigate it to /search?q="what ever search result is". but i wan't show any thing it will send it to search page where all workflows and apps are listed. @frikky

**Comment by ayush0033** [comment]
https://github.com/Shuffle/Shuffle/assets/64920526/463d0dc1-cba7-4d1d-9322-907ffb7b0b89

**Comment by ayush0033** [comment]
@frikky any suggestion ???
