### ISSUE TITLE
Make it possible to edit the name of a saved app authentication

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1144]
Path: /admin?tab=app_auth

Right now, this is only possible for the parameters, not the name. This should also make it **NOT** possible to change auth if the app is Oauth2

![image](https://github.com/Shuffle/Shuffle/assets/5719530/fc74b6a2-0014-4c00-ae01-fb6615b6b92f)

**Comment by PratyushChauhan** [comment]
Hey @0x0elliot I'd like to take a shot at this. Please assign this to me.

**Comment by 0x0elliot** [comment]
hey @PratyushChauhan, sure let me do that.

**Comment by 0x0elliot** [comment]
@PratyushChauhan updates? ever got shuffle working?

**Comment by PratyushChauhan** [comment]
Sadly nope. I didn't get enough time to experiment more. You can un assign me. @0x0elliot

**Comment by frikky** [comment]
This is done
