### ISSUE TITLE
Add API for permanently deleting ALL data for a file

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1172]
Right now if you delete file with  `DELETE /api/v1/files/<file_id>`  it deletes the file, but keeps the metadata. Add a query to be added that permanently deletes the whole file ID.

Sample query:
`DELETE /api/v1/files/<file_id>?remove_metadata=true`

`remove_metadata = true` will then delete it all properly.

**Comment by 0x0elliot** [comment]
i will take care of this today.

**Comment by 0x0elliot** [comment]
https://github.com/Shuffle/shuffle-shared/pull/26

**Comment by frikky** [comment]
Done \o/
