### ISSUE TITLE
Onboarding - Welcome page design

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1188]
Implement the design and functionality from here: https://www.figma.com/file/ACFoR4zVBm9k7inC45vnR8/Shuffle-Web?type=design&mode=design

Start with the "Help us get to know you" page, then do the "Find your apps", before "Start Using Workflow"

**Comment by ayush0033** [comment]
first tab is mostly done.

![Image](https://github.com/Shuffle/Shuffle/assets/64920526/429ece64-f88c-4852-b70e-9c4ce56530ab)

**Comment by ayush0033** [comment]
PR for welcome pages designs - onBoarding pages :
https://github.com/Shuffle/shaffuru/pull/207
