### ISSUE TITLE
Abstract serverless functions to allow multi cloud

### ISSUE THREAD

**Issue by peterclemenko** [Shuffle/Shuffle#12]
The ability to run in AWS or Azure for the serverless functions would be very useful, especially when dealing with stuff that needs to run in a cleared environment (AWS is the only cloud host certified to run TS/SCI and Azure and AWS can run Secret). It would also be useful for when you're at a shop that only supports one of the other clouds (the shop I'm at is AWS and politics would get in the way of using GCP)

**Comment by frikky** [comment]
Hey! 

That's a great idea. I'll check whether OpenCloud or something similar supports it, as I already have an implementation working for GCP. Porting shouldn't be too hard at that point :)

Fredrik

**Comment by frikky** [comment]
Closing as we are moving towards simplifying with K8s/docker instead
