### ISSUE TITLE
Can't change API key from /admin?tab=users 

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1203]
To change your API key, you have to use the /settings for now. This uses the same API, but somehow it assumes you're a different user altogether? It shouldn't be possible to reset the api-key of another account.

**Comment by SoNiC-HeRE** [comment]
Hi @frikky @0x0elliot I am interested in working on this issue. Can you please assign me this

**Comment by 0x0elliot** [comment]
sure! do you know what to do here?

**Comment by 0x0elliot** [comment]
@frikky can you give @SoNiC-HeRE more context here? 

@SoNiC-HeRE be sure to ask questions. i don't think this issue by itself contains enough context for you to get done with anything.

**Comment by frikky** [comment]
In short: when logged in, and you try to reset your API key from the /admin?tab=users location, it doesn't work the same as when trying to reset it on the /settings page

**Comment by 0x0elliot** [comment]
@SoNiC-HeRE does this make sense to you?

**Comment by LalitDeore** [comment]
hey @frikky in this issue when we reset API key from the settings tab new API is generated and it is consider as of new user and when we reset from admin it was not working like this did i get this correct? if yes could you please guide me what will be our approach to address this issue?

**Comment by frikky** [comment]
> hey @frikky in this issue when we reset API key from the settings tab new API key is generated and it is consider as of new user and when we reset from admin it is not working like this did i get this correct? if yes could you please guide me what will be our approach to address this issue?

Hey!

I just retested it all, and it seems to work after some edits we most likely did in the last release (1.3.0). Too many issues to keep track of. The point was for both of them to reset the same API key for your own user only.

Closing this so no one else goes on their way trying to fix it.
