### ISSUE TITLE
Getting error while building backend image 

### ISSUE THREAD

**Issue by yogeshgurjar127** [Shuffle/Shuffle#1204]
![image](https://github.com/Shuffle/Shuffle/assets/118437260/1afc7ea6-32aa-4367-b40e-b1e0521d13e9)
I am using shuffle-shared v0.4.46

**Comment by frikky** [comment]
> ![image](https://user-images.githubusercontent.com/118437260/270960623-1afc7ea6-32aa-4367-b40e-b1e0521d13e9.png) I am using shuffle-shared v0.4.46

Hey!

Are you using the 1.3.0 branch?

**Comment by frikky** [comment]
Got an email this was solved :)
