### ISSUE TITLE
Create Notification Pool for identical Notifications as to not spam everything

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1228]
Avoid things going VERY wrong. Bucketing questions:
- What kind of period works?
- Is the data amount important?
- Should it be configurable? 
- What does "TYPE" really mean? Is it per workflow? Per name? Per app? (probably per name)

MOST IMPORTANT:
- Don't spam down the notification workflow.

**Comment by 0x0elliot** [comment]
interesting observation: notifications just straight up don't work for workflows triggered by a trigger at all :P
