### ISSUE TITLE
run shuffle behind a reverse proxy

### ISSUE THREAD

**Issue by dsek** [Shuffle/Shuffle#1233]
Hello,

Problem/Requirement:
As I needed to run shuffle behind a nginx reverse proxy (openresty with openidc) I wrote a bash script for patching all necessary files of a clean shuffle frontend git checkout (version 1.3.0).

How does it work:
Just place the 2 attached files to the git checkout root of shuffle/shuffle and run the bash script "enable_subpathing_for_shuffle.sh" which is going to patch the source to have shuffle running at "/shuffle" instead of "/".

Don't forget to execute a `chmod 700 enable_subpathing_for_shuffle.sh` or to run it prefixing `bash enable_subpathing_for_shuffle.sh`

Example:
`./enable_subpathing_for_shuffle.sh`
`./enable_subpathing_for_shuffle.sh /myshufflereverseproxied`
`./enable_subpathing_for_shuffle.sh /whatever`

After the script has finished `docker build -t ghcr.io/shuffle/shuffle-frontend:latest .` will be called automatically.

Finally an example configuration output for nginx is presented. 

Maybe this is helpful to somebody else too.

Bye and greetings,
dsek

[enable_subpathing_for_shuffle.zip](https://github.com/Shuffle/Shuffle/files/13216195/enable_subpathing_for_shuffle.zip)

**Comment by frikky** [comment]
@0x0elliot could you make a PR from this and merge it in? 

It has to do with automatic changes to frontend URL's during build of the frontend as to make it work with differing paths 

E.g. if you want it to run like http://domain/shuffle/test/api/v1/...

then this makes it possible to inject that "/shuffle/test" part before the API :)

Cheers @dsek!

**Comment by 0x0elliot** [comment]
> @0x0elliot could you make a PR from this and merge it in?
> 
> It has to do with automatic changes to frontend URL's during build of the frontend as to make it work with differing paths
> 
> E.g. if you want it to run like http://domain/shuffle/test/api/v1/...
> 
> then this makes it possible to inject that "/shuffle/test" part before the API :)
> 
> Cheers @dsek!

sure why not. let me take a look.

**Comment by 0x0elliot** [comment]
@milesflo Thanks for the contribution. This script essentially alters all the paths in the jsx code.

i don't know if i like this solution in particular.

- Why edit the paths the way you are here when you can simply edit the globalUrl and fit it in somehow?
- All the window.location.origin, path etc mentions can be fixed accordingly as well for this.

Is there really no solution where we can make the react code be ready for a reverse proxy mode and have a nginx configurations that support it? (if the latter is needed)

**Comment by dsek** [comment]
@0x0elliot: it is not only about globalUrl (now on the basis of the source code). it would be nice if so ... but sadly: it is not ... therefore the "patching"

**Comment by frikky** [comment]
Closing as we got this solved
