### ISSUE TITLE
Fix dockerbuild github action

### ISSUE THREAD

**Issue by 0x0elliot** [Shuffle/Shuffle#1242]
Right now, [this](https://github.com/Shuffle/Shuffle/blob/main/.github/workflows/dockerbuild.yaml) github action builds for all changes pushed to main. This becomes annoying when I am just updating a README.md file. Can we make this github action not run when markdown files are pushed? 

Other smarter filters are also appreciated. I hate unnecessary builds.

**Comment by SainiAditya1** [comment]
@0x0elliot , I want to work on this issue please assign this .

**Comment by 0x0elliot** [comment]
@imlakshay08 i dislike the fact that you stepped a toe there. it is important that we ask before we get to work on things so that we are looking out for the community :)

**Comment by 0x0elliot** [comment]
@SainiAditya1 i am assigning you to this issue. please work on it. apologies for the late response!

refer to @@imlakshay08's PR to see what he did wrong and how you can fix it.

**Comment by imlakshay08** [comment]
> @imlakshay08 i dislike the fact that you stepped a toe there. it is important that we ask before we get to work on things so that we are looking out for the community :)

Well, really sorry about this and for the late reply, apologies for both. Actually, I am kinda newbie in open source as well and still learning. I'll take this as a feedback and keep in mind before contributing in future as well. Thank you.

**Comment by 0x0elliot** [comment]
@imlakshay08 don't worry about it! let me help give you another easier issue. why don't you join our discord and ping me there.

**Comment by imlakshay08** [comment]
> @imlakshay08 don't worry about it! let me help give you another issue. why don't you join our discord and ping me there.
Could you provide link for it?

**Comment by 0x0elliot** [comment]
> > @imlakshay08 don't worry about it! let me help give you another issue. why don't you join our discord and ping me there.
> 
> Could you provide link for it?

it's in our README.md under support section.
