### ISSUE TITLE
Docs section Sidebar UI Enhancement

### ISSUE THREAD

**Issue by Monilprajapati** [Shuffle/Shuffle#1254]
**Is your feature request related to a problem? Please describe.**
Sidebar, which really plays an important role in using the page efficiently, So in the Docs section, the UI of the sidebar looks so basic, which affects the user experience of the website.

**Describe the solution you'd like**
I will change the sidebar UI by making an efficient use of Material UI's Collapse API. I have shared a screenshot of the outcome after applying the changes.

**Screenshots of where and how**
Current UI of the sidebar section: 

![WhatsApp Image 2023-11-08 at 22 25 45_eea8a10d](https://github.com/Shuffle/Shuffle/assets/99136041/9c9af38e-40b4-4b5f-8c20-a93e70d3b9b6)

After making the changes:

![WhatsApp Image 2023-11-08 at 22 25 27_c92cc6f2](https://github.com/Shuffle/Shuffle/assets/99136041/bc5cf327-aa15-44d1-bcac-4f6bfecd37ff)

**Comment by Monilprajapati** [comment]
Hey, @frikky and @0x0elliot! I have noticed that this UI enhancement is really needed for a better user experience.
I would love to work on this issue.

**Comment by frikky** [comment]
> Hey, @frikky and @0x0elliot! I have noticed that this UI enhancement is really needed for a better user experience. I would love to work on this issue.

Hey! This looks nice! Could you make it work a bit better with the actual content as well? The distance between the sidebar and is badly positioned and such. 

Relevant:
- Make it all be centered and have a maxwidth (as to not have the sidebar super far left on wide screens) 
- Make the sidebar and the content be close to each other
- I'm unsure whether the Mobile sidebar works properly or not

**Comment by Monilprajapati** [comment]
> > Hey, @frikky and @0x0elliot! I have noticed that this UI enhancement is really needed for a better user experience. I would love to work on this issue.
> 
> Hey! This looks nice! Could you make it work a bit better with the actual content as well? The distance between the sidebar and is badly positioned and such.
> 
> Relevant:
> 
> * Make it all be centered and have a maxwidth (as to not have the sidebar super far left on wide screens)
> * Make the sidebar and the content be close to each other
> * I'm unsure whether the Mobile sidebar works properly or not

It is working really badly in mobile because it is not as responsive as it needs to be!! I can also fix that, but it'll take more time. like i can add one side drawer icon through which you can access the sidebar very easily.

**Comment by Monilprajapati** [comment]
Hey @frikky  What about this?

Preview :

![image](https://github.com/Shuffle/Shuffle/assets/99136041/3213ddbb-b381-4e29-8f29-4a83408e8700)

**Comment by Monilprajapati** [comment]
Hey @frikky I have raised PR for that sidebar part for now only.

**Comment by Monilprajapati** [comment]
Hey @0x0elliot check this out!!

**Comment by frikky** [comment]
Hey @Monilprajapati - we had a chat about this, and were wondering if you had some idea for how to change the colorscheme of the sidebar to make it look more appealing?

**Comment by Monilprajapati** [comment]
> Hey @Monilprajapati - we had a chat about this, and were wondering if you had some idea for how to change the colorscheme of the sidebar to make it look more appealing?

Yeah, we can also do that, but for that, the designer team needs to work on it. For now, I think just add this UI for the sidebar. Later on, we can change the color scheme and other stuff.
