### ISSUE TITLE
[ERROR] Error in initial database connection

### ISSUE THREAD

**Issue by jutana** [Shuffle/Shuffle#1271]
spinning up the docker container - everything is fine but opensearch does not launch - after grabbing the docker logs i see the below. not too familar with how docker will lookup hostnames, do i need to create a host file or something? this default docker-compose.yml 

**[ERROR] Error in initial database connection. Retrying in 5 seconds. dial tcp: lookup shuffle-opensearch on 127.0.0.11:53: no such host**

tried running this on debian 12 lxc container ubuntu 22 lcx container as well as debian 12 VM 

Docker version 24.0.7, build afdd53b

**Comment by frikky** [comment]
Hey,

please send the logs from within the Opensearch container:

`docker logs shuffle-opensearch`

**Comment by aprile007** [comment]
Hi thanks see below

**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on Amazon Linux release 2023 (Amazon Linux)
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-2.11.0
Detected OpenSearch Security Version: 2.11.0.0
/usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.
Enabling OpenSearch Security Plugin
Disabling execution of /usr/share/opensearch/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin
./opensearch-docker-entrypoint.sh: line 70:    31 Killed                  "$@" "${opensearch_opts[@]}"

**Comment by frikky** [comment]
> Hi thanks see below
> 
> ** This tool will be deprecated in the next major release of OpenSearch ** ** [opensearch-project/security#1755](https://github.com/opensearch-project/security/issues/1755) **
> 
> OpenSearch Security Demo Installer ** Warning: Do not use on production or public reachable systems ** Basedir: /usr/share/opensearch OpenSearch install type: rpm/deb on Amazon Linux release 2023 (Amazon Linux) OpenSearch config dir: /usr/share/opensearch/config OpenSearch config file: /usr/share/opensearch/config/opensearch.yml OpenSearch bin dir: /usr/share/opensearch/bin OpenSearch plugins dir: /usr/share/opensearch/plugins OpenSearch lib dir: /usr/share/opensearch/lib Detected OpenSearch Version: x-content-2.11.0 Detected OpenSearch Security Version: 2.11.0.0 /usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit. Enabling OpenSearch Security Plugin Disabling execution of /usr/share/opensearch/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin ./opensearch-docker-entrypoint.sh: line 70: 31 Killed "$@" "${opensearch_opts[@]}"

That's typically a problem with memory. How much do you have on your machine? It requires 4Gb (2Gb used by database)

**Comment by jutana** [comment]
Thanks, I moved back to a VM vs container and allocated more mem & disk space, also while setting up the VM i removed swap partition just in case! 

Thanks for  your help!
