### ISSUE TITLE
Encryption/Decryption of Auth sometimes not set as it should

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1286]
There are cases where Auth specified by the user doesn't use the `ENCRYPTION_MODIFIER`, or where the auth is automatically decrypted fully, leading to it being cleartext.

This should NEVER happen for anything tagged as `"encrypted": true`

Update:
- When updating an auth, it apparently doesn't use the `ENCRYPTION MODIFIER`

**Comment by tbi88** [comment]
I verified this works fine now in the latest nightly version. After updating the app-auth name, data is encrypted again.

**Comment by frikky** [comment]
> I verified this works fine now in the latest nightly version. After updating the app-auth name, data is encrypted again.

Cheers. Closing this issue as resolved.
