### ISSUE TITLE
Execution get stuck when path conditions are not met

### ISSUE THREAD

**Issue by samuelmonsempessenthorus** [Shuffle/Shuffle#1299]
**Describe the bug**
Execution get stuck when path conditions are not met

**To Reproduce**
1. Install Shuffle
2. Create a workflow with a condition
3. Run the workflow in a way it don't trigger the condition

![image](https://github.com/Shuffle/Shuffle/assets/139971708/1544f4fb-260e-4f7d-ba02-e71d8e867ea4)

**Expected behavior**
If too much executions get stucks it stucks all the executions

**Comment by frikky** [comment]
> **Describe the bug** Execution get stuck when path conditions are not met
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install Shuffle
> 2. Create a workflow with a condition
> 3. Run the workflow in a way it don't trigger the condition
> 
> ![image](https://private-user-images.githubusercontent.com/139971708/294511866-1544f4fb-260e-4f7d-ba02-e71d8e867ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTY1NDMsIm5iZiI6MTcwNDcxNjI0MywicGF0aCI6Ii8xMzk5NzE3MDgvMjk0NTExODY2LTE1NDRmNGZiLTI2MGUtNGY3ZC1iYTAyLWU3MWQ4ZTg2N2VhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxMjE3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmM2MzExNTM4NTM5ZWJjZjdjZmRiYmQxNWJkYjk1MjQ3ZjExNzQ0MjExMDVjNjk5NmMxZGJjZmYxM2M3NDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OLU28RQPtw8rmpJ3MHbedhEKfLGZUlOX7t1qJkz7UGA)
> 
> **Expected behavior** If too much executions get stucks it stucks all the executions

Thanks! I think this is a bug introduced in 1.3.0, further solved in the latest nightly worker, for which the fixes will be propagated soon.

**Comment by frikky** [comment]
Closing this issue - @samuelmonsempessenthorus if this persists, please do reach back out.
