### ISSUE TITLE
app_bask.py Parameter parsing bug

### ISSUE THREAD

**Issue by iifiigii** [Shuffle/Shuffle#1306]
![image](https://github.com/Shuffle/Shuffle/assets/38291119/57b2761f-36e8-4908-9989-92a1f15aaa4b)
As I use item.#0-2 to set a FOR LOOP, I got a error and log as below:

Traceback (most recent call last):
File "/app/walkoff_app_sdk/app_base.py", line 3283, in execute_action
check, value, is_loop = parse_params(action, fullexecution, parameter, self)
File "/app/walkoff_app_sdk/app_base.py", line 2705, in parse_params
value, is_loop = get_json_value(fullexecution, to_be_replaced)
File "/app/walkoff_app_sdk/app_base.py", line 2308, in get_json_value
data, is_loop = recurse_json(basejson, parsersplit[1:])
File "/app/walkoff_app_sdk/app_base.py", line 2102, in recurse_json
if seconditem.lower() == "max" or seconditem.lower() == "last" or firstitem.lower() == "end":
AttributeError: 'int' object has no attribute 'lower'

In "backend/app_sdk/app_base.py" 2065-2085 line, "firstitem" may be converted to INT and call firstitem.lower() after. Need more type judge here.

source code:
```python
  else:
      print("[INFO] In ELSE - handling %s and %s" % (firstitem, seconditem))
      if isinstance(firstitem, str):
          if firstitem.lower() == "max" or firstitem.lower() == "last" or firstitem.lower() == "end": 
              firstitem = len(basejson)-1
          elif firstitem.lower() == "min" or firstitem.lower() == "first": 
              firstitem = 0
          else:
              firstitem = int(firstitem)
      else:
          **_firstitem = int(firstitem)_**
      if isinstance(seconditem, str): 
          if seconditem.lower() == "max" or seconditem.lower() == "last" or **_firstitem.lower() == "end"_**: 
              seconditem = len(basejson)-1
          elif seconditem.lower() == "min" or seconditem.lower() == "first": 
              seconditem = 0
          else:
              seconditem = int(seconditem)
      else:
          seconditem = int(seconditem)
```

**Comment by frikky** [comment]
> ![image](https://private-user-images.githubusercontent.com/38291119/299175954-57b2761f-36e8-4908-9989-92a1f15aaa4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODUzMDAsIm5iZiI6MTcwNjA4NTAwMCwicGF0aCI6Ii8zODI5MTExOS8yOTkxNzU5NTQtNTdiMjc2MWYtMzZlOC00OTA4LTk5ODktOTJhMWYxNWFhYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA4MzAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNjMxYjM4NTJlNWQyMTU3YTZkYTQyZDJjZWY0ZTEwNGRhMmZiZGYwNTk3ZWU5YTExMzVmZTczNzYyNWQxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYCaIT5g7tBx3NRpsjwIzOfu3g9e7VVcXxM_eIjYdoc) As I use item.#0-2 to set a FOR LOOP, I got a error and log as below:
> 
> Traceback (most recent call last): File "/app/walkoff_app_sdk/app_base.py", line 3283, in execute_action check, value, is_loop = parse_params(action, fullexecution, parameter, self) File "/app/walkoff_app_sdk/app_base.py", line 2705, in parse_params value, is_loop = get_json_value(fullexecution, to_be_replaced) File "/app/walkoff_app_sdk/app_base.py", line 2308, in get_json_value data, is_loop = recurse_json(basejson, parsersplit[1:]) File "/app/walkoff_app_sdk/app_base.py", line 2102, in recurse_json if seconditem.lower() == "max" or seconditem.lower() == "last" or firstitem.lower() == "end": AttributeError: 'int' object has no attribute 'lower'
> 
> In "backend/app_sdk/app_base.py" 2065-2085 line, "firstitem" may be converted to INT and call firstitem.lower() after. Need more type judge here.
> 
> source code:
> 
> ```python
>   else:
>       print("[INFO] In ELSE - handling %s and %s" % (firstitem, seconditem))
>       if isinstance(firstitem, str):
>           if firstitem.lower() == "max" or firstitem.lower() == "last" or firstitem.lower() == "end": 
>               firstitem = len(basejson)-1
>           elif firstitem.lower() == "min" or firstitem.lower() == "first": 
>               firstitem = 0
>           else:
>               firstitem = int(firstitem)
>       else:
>           **_firstitem = int(firstitem)_**
>       if isinstance(seconditem, str): 
>           if seconditem.lower() == "max" or seconditem.lower() == "last" or **_firstitem.lower() == "end"_**: 
>               seconditem = len(basejson)-1
>           elif seconditem.lower() == "min" or seconditem.lower() == "first": 
>               seconditem = 0
>           else:
>               seconditem = int(seconditem)
>       else:
>           seconditem = int(seconditem)
> ```

Thanks!

Could you point me to what the data was? If it's just a string casting problem, it shouldn't be a problem at all :)

**Comment by iifiigii** [comment]
Front node is {tool:“Shuffle-tool”,action:"Execution Python",code:"print([i for i in range(10)])".
Error node is  {tool:“Shuffle-tool”,action:"Execution Python",code:"x = $shuffle_tools_2.message.#0-2".
When I use "$shuffle_tools_2.message.#", it doing well.

**Comment by iifiigii** [comment]
The commit above looks perfect, Thanks!
