### ISSUE TITLE
API_URL incorrect

### ISSUE THREAD

**Issue by 69ares** [Shuffle/Shuffle#1313]
**Describe the bug**
Even if I enter a URL to contact the API server, orobus tries to contact 127.0.0.1

**Expected behavior**
Contact the correct API_URL server

**Screenshots**
![Screenshot 2024-01-31 115634](https://github.com/Shuffle/Shuffle/assets/35406032/2158f255-0ee4-40ba-91dc-257262e9b579)
![Screenshot 2024-01-31 115432](https://github.com/Shuffle/Shuffle/assets/35406032/64cb4f1f-c229-4069-83a6-54f077fbc909)
![Screenshot 2024-01-31 115408](https://github.com/Shuffle/Shuffle/assets/35406032/83be7863-8dbc-476c-91aa-86623bd7eae8)
![Screenshot 2024-01-31 115346](https://github.com/Shuffle/Shuffle/assets/35406032/86f2e8f3-b39c-4a5c-86fc-1c990caffef4)

**Debug logs (NOT APPLICABLE FOR CLOUD)**
ConnectionError - HTTPSConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /objects/services (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe0a1280eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by 69ares** [comment]
I solved.
Simply change the workflow authentication from the admin panel

![image](https://github.com/Shuffle/Shuffle/assets/35406032/a12b49a4-10b6-4a01-b96b-3a9db31ca594)

**Comment by frikky** [comment]
> **Describe the bug** Even if I enter a URL to contact the API server, orobus tries to contact 127.0.0.1
> 
> **Expected behavior** Contact the correct API_URL server
> 
> **Screenshots** ![Screenshot 2024-01-31 115634](https://private-user-images.githubusercontent.com/35406032/301135179-2158f255-0ee4-40ba-91dc-257262e9b579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTk3MzAsIm5iZiI6MTcwNjY5OTQzMCwicGF0aCI6Ii8zNTQwNjAzMi8zMDExMzUxNzktMjE1OGYyNTUtMGVlNC00MGJhLTkxZGMtMjU3MjYyZTliNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDExMTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNWZkODkxZTQ1MmM5YTAxZmIwMTJmZWZhNDFlZTNjNzc2Y2RlNWFhMjU1Yzk3YWU1NTJiNTFmMWYwY2Q4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rSmV18qCK6nOKG_JlOMlhRM0coOWklBbxeOo_m1bmrk) ![Screenshot 2024-01-31 115432](https://private-user-images.githubusercontent.com/35406032/301135196-64cb4f1f-c229-4069-83a6-54f077fbc909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTk3MzAsIm5iZiI6MTcwNjY5OTQzMCwicGF0aCI6Ii8zNTQwNjAzMi8zMDExMzUxOTYtNjRjYjRmMWYtYzIyOS00MDY5LTgzYTYtNTRmMDc3ZmJjOTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDExMTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODVmNGEwZjMxYTA0YTIxMjliYjdlNjFjOTZlMTU3NzJkNmQ1ZGZjZWZlZjI4NDliZDNkODU5OTBiNGNlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jBaIGIOrxm5xY0Ur0iHVSYt5Uc96Vgk4mHbULccbjMA) ![Screenshot 2024-01-31 115408](https://private-user-images.githubusercontent.com/35406032/301135214-83be7863-8dbc-476c-91aa-86623bd7eae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTk3MzAsIm5iZiI6MTcwNjY5OTQzMCwicGF0aCI6Ii8zNTQwNjAzMi8zMDExMzUyMTQtODNiZTc4NjMtOGRiYy00NzZjLTkxYWEtODY2MjNiZDdlYWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDExMTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MDIzNGRjMjdjNzRhMjlkMTg5OWJmZGFlZDBkYWU2YTJkZjE2N2I1OTUzZjdjNzE1ZTdhYTQ3ZmQ1OGE5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pwYy0KTx1Yw82kCXg6QljqmyBQs6dZPWt7-ZBprl0AY) ![Screenshot 2024-01-31 115346](https://private-user-images.githubusercontent.com/35406032/301135225-86f2e8f3-b39c-4a5c-86fc-1c990caffef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTk3MzAsIm5iZiI6MTcwNjY5OTQzMCwicGF0aCI6Ii8zNTQwNjAzMi8zMDExMzUyMjUtODZmMmU4ZjMtYjM5Yy00YTVjLTg2ZmMtMWM5OTBjYWZmZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDExMTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZjY5ZTQyZjI4MzllZTViNGU5NDA3ZTMwZTg5NjA0ZDhlZmE5YzBjYTQzZGQ5MTc0Njg1ZjlmZTUxZTlhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S_Bkgc9fGJEbKY3TKfZXHXr1EEQrMxecMkY-qi3uKTs)
> 
> **Debug logs (NOT APPLICABLE FOR CLOUD)** ConnectionError - HTTPSConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /objects/services (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe0a1280eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Hey!

As you can see, it's connecting to 127.0.0.1:5665. This is due to the configuration you gave to the app in your Workflow, not in the App.

Apps are JUST templates - this means they may have some defaults. You most likely have wrong configuration for the "url" field in the app authentication :)

**Comment by LalitDeore** [comment]
@69ares has solved this issue.
