### ISSUE TITLE
Shuffle backend ignores proxy settings

### ISSUE THREAD

**Issue by x32xx23x** [Shuffle/Shuffle#1318]
**Describe the bug**
After setting the HTTP_PROXY and HTTPS_PROXY, the backend acknowledges them.

```
shuffle-backend | 2024/02/01 11:34:20 [INFO] Running with HTTP proxy http://proxy:3128 (env: HTTP_PROXY)
shuffle-backend | 2024/02/01 11:34:20 [INFO] Running with HTTPS proxy http://proxy:3128 (env: HTTPS_PROXY)
```

But then it tries to resolve the url's domain.

```
shuffle-backend | 2024/02/01 11:35:21 [WARNING] Error getting app with ID 971706758e274c2e4083f2621fb5a6f7 (app config): App doesn't exist. Starting remote download(2)
shuffle-backend | 2024/02/01 11:35:21 Downloading API from https://shuffler.io/api/v1/apps/971706758e274c2e4083f2621fb5a6f7/config
shuffle-backend | 2024/02/01 11:35:26 [ERROR] Failed running auto-download request for 971706758e274c2e4083f2621fb5a6f7: Get "https://shuffler.io/api/v1/apps/971706758e274c2e4083f2621fb5a6f7/config": dial tcp: lookup shuffler.io: Try again
```

I confirm through a packet capture that these DNS queries are sent. Moreover nothing related to these requests appear in the proxy logs.

**To Reproduce**
1. Set the `HTTP_PROXY` and `HTTPS_PROXY` variables for `shuffle-backend`
2. Trigger an http request by starting an app that doesn't exist.

**Expected behavior**
Usual HTTP proxy behavior, send http request to the proxy, let it do the name resolution.

**Comment by frikky** [comment]
> **Describe the bug** After setting the HTTP_PROXY and HTTPS_PROXY, the backend acknowledges them.
> 
> ```
> shuffle-backend | 2024/02/01 11:34:20 [INFO] Running with HTTP proxy http://proxy:3128 (env: HTTP_PROXY)
> shuffle-backend | 2024/02/01 11:34:20 [INFO] Running with HTTPS proxy http://proxy:3128 (env: HTTPS_PROXY)
> ```
> 
> But then it tries to resolve the url's domain.
> 
> ```
> shuffle-backend | 2024/02/01 11:35:21 [WARNING] Error getting app with ID 971706758e274c2e4083f2621fb5a6f7 (app config): App doesn't exist. Starting remote download(2)
> shuffle-backend | 2024/02/01 11:35:21 Downloading API from https://shuffler.io/api/v1/apps/971706758e274c2e4083f2621fb5a6f7/config
> shuffle-backend | 2024/02/01 11:35:26 [ERROR] Failed running auto-download request for 971706758e274c2e4083f2621fb5a6f7: Get "https://shuffler.io/api/v1/apps/971706758e274c2e4083f2621fb5a6f7/config": dial tcp: lookup shuffler.io: Try again
> ```
> 
> I confirm through a packet capture that these DNS queries are sent. Moreover nothing related to these requests appear in the proxy logs.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Set the `HTTP_PROXY` and `HTTPS_PROXY` variables for `shuffle-backend`
> 2. Trigger an http request by starting an app that doesn't exist.
> 
> **Expected behavior** Usual HTTP proxy behavior, send http request to the proxy, let it do the name resolution.

Looks like you found one of the APIs that are self-defining its HTTP client instead of using the one that takes care of proxies. 

When this is done for the backend, please change your backend version in docker-compose to nightly and docker-compose down => up: https://github.com/Shuffle/Shuffle/actions/runs/7742100944/job/21110447170

**Comment by x32xx23x** [comment]
Hi. Thanks for your message.

I did what you told me:
```
$ docker ps | grep shuffle
41fdfd3f3f44   ghcr.io/shuffle/shuffle-frontend:latest      "/entrypoint.sh ngin…"   5 minutes ago   Up 5 minutes             0.0.0.0:3001->80/tcp, :::3001->80/tcp, 0.0.0.0:3443->443/tcp, :::3443->443/tcp                                                              shuffle-frontend
979944a95bbf   opensearchproject/opensearch:2.11.0          "./opensearch-docker…"   5 minutes ago   Up 5 minutes             9300/tcp, 9600/tcp, 0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 9650/tcp                                                                     shuffle-opensearch
96b7bc452d2f   ghcr.io/shuffle/shuffle-backend:nightly      "./webapp"               5 minutes ago   Up 5 minutes             0.0.0.0:5001->5001/tcp, :::5001->5001/tcp
                                                                              shuffle-backend
a36dc4979f4c   ghcr.io/shuffle/shuffle-orborus:latest       "./orborus"              5 minutes ago   Up 5 minutes
                                                                              shuffle-orborus
$ docker image ls | head -n2
REPOSITORY                                      TAG                                       IMAGE ID       CREATED         SIZE
ghcr.io/shuffle/shuffle-backend                 nightly                                   5c2dbbe1053d   2 hours ago     80.6MB
```

But the outcome is exactly the same as described in the issue's description.

**Comment by x32xx23x** [comment]
Any news @frikky ?
