### ISSUE TITLE
Cancel Button Saving Edits Instead of Discarding Changes

### ISSUE THREAD

**Issue by satti-hari-krishna-reddy** [Shuffle/Shuffle#1329]
**Describe the bug**
The current behavior of the cancel button in the `conditionsModal` is not aligning with its intended purpose. When edited a text field, clicking the cancel button should discard any changes made without saving them. However, in the current implementation, clicking the cancel button is saving the edits made to the text field

**To Reproduce**
1. In any of your workflow try add a condition  (e.g., "true" Does Not Equal "false") and save it .
2. Reopen the condition and modify the content (e.g., change to "false" Does Not Equal "false")
3. Click on the cancel button to discard the changes.

**Expected behavior**
The text field should revert to its previous state ("true" Does Not Equal "false") after clicking the cancel button, discarding any edits made in step 3.

**Actual behavior**
 The cancel button is saving the edits made in step 3

**Screenshots**

1.
![Screenshot (40)](https://github.com/Shuffle/Shuffle/assets/141043716/3f64c163-369d-43e0-81d9-f0b45c2f5081)

2.
![Screenshot (41)](https://github.com/Shuffle/Shuffle/assets/141043716/69fd9d4a-3770-45e2-86c9-63d9fc251422)

3.
![Screenshot (42)](https://github.com/Shuffle/Shuffle/assets/141043716/13fca322-71db-4dcd-bfcd-20b6a132425c)

4.
![Screenshot (43)](https://github.com/Shuffle/Shuffle/assets/141043716/a151701a-c131-4f1c-afb2-08c137e4dbda)

**Comment by frikky** [comment]
You got this 🔥
