### ISSUE TITLE
Please provide an execution argument  

### ISSUE THREAD

**Issue by samira-karimi-elfiman** [Shuffle/Shuffle#1330]
**Describe the bug**
I created a workflow in a version of Shuffle that I installed locally on my system. I exported it and import it in the version of Shuffle that I installed on the server. Workflow has subflow. When I run the workflow, I get a message like this.

![image](https://github.com/Shuffle/Shuffle/assets/61731682/87a19eeb-598b-42ed-a5e2-5ca814c110e0)

This message is not seen when I run the workflow in my local system. How can I solve this problem? I don't want him to ask me. I want it to take the value from the previous node, which is Outlook, like the local mode, and continue running.

in local and server, I installed docker base of shuffle in latest mode

this is setting of subflow

![image](https://github.com/Shuffle/Shuffle/assets/61731682/dc772373-4c54-4ce2-a890-07c008b8dc3b)

**Comment by tesla999936** [comment]
what is your result when you clicked on `RUN ANYWAY` ? did you got the expected ouput ?

**Comment by samira-karimi-elfiman** [comment]
run workflow successfully

**Comment by frikky** [comment]
> The workflow executes successfully

Hey! Good question.

In short: This was a feature added to help users when `$exec` is used in the workflow somewhere. It will not show up if you have an execution argument filled in, or if $exec is not used anywhere.

It's a helper to ensure your workflow finishes no matter what :)
