### ISSUE TITLE
Clicking on "About us" on the footer on the landing page goes to documentation similar to the "Documentation" link right beside.

### ISSUE THREAD

**Issue by Abdullah-03** [Shuffle/Shuffle#1332]
**Describe the bug**
Clicking on "About us" on the footer redirects to documentation rather than an "About us page". Similar behaviour is already available with the "Documentation" link right beside.

**To Reproduce**
Steps to reproduce the behaviour:
1. Head over to https://shuffler.io/ (or any other page where the footer is visible).
2. Scroll to the end of the landing page.
3. Click "About us" link in the footer.
...

**Expected behaviour**
An "About us" page should appear. One such populated view exists in the frontend views directory but it does not get rendered.

**Screenshots**
![Screenshot 2024-02-18 114756](https://github.com/Shuffle/Shuffle/assets/43924652/3fd893be-3df7-4796-a5f6-195979b9d497)

**Comment by frikky** [comment]
Thanks. It was meant to go to /docs/about and will be fixed in the next release
