### ISSUE TITLE
Backend and orborus connection issues

### ISSUE THREAD

**Issue by Farru19** [Shuffle/Shuffle#1341]
1.  Deployed an lxc 22.04 ubuntu container in proxmox with 2 cores and 4g ram. 
2. Followed the installation guide.md
3. When I visti the UI @ port 3001 It shows this : 
![Screenshot from 2024-02-28 16-10-28](https://github.com/Shuffle/Shuffle/assets/54806674/1d89b3f3-6a36-490c-9eb9-0652847cb0dd)
4. Commented ulimits because it has issues starting and creating opensearch container and showed docker daemon error.
unlimits :      
 memlock:
        soft: -1
        hard: -1
        nofile:
        soft: 65536 
        hard: 65536

- Attached log files for futher inspection and possible solution.
[shuffle-backend_logs.txt](https://github.com/Shuffle/Shuffle/files/14432628/shuffle-backend_logs.txt)
[shuffle-frontend_logs.txt](https://github.com/Shuffle/Shuffle/files/14432629/shuffle-frontend_logs.txt)
[shuffle-opensearch_logs.txt](https://github.com/Shuffle/Shuffle/files/14432631/shuffle-opensearch_logs.txt)
[shuffle-orborus_logs.txt](https://github.com/Shuffle/Shuffle/files/14432638/shuffle-orborus_logs.txt)

**Comment by frikky** [comment]
Hey! Based on the Opensearch logs, it is failing to allocate memory for your server. 

```
[2024-02-28T10:36:25,170][WARN ][o.o.b.JNANatives         ] [shuffle-opensearch] Unable to lock JVM Memory: error=12, reason=Cannot allocate memory
[2024-02-28T10:36:25,172][WARN ][o.o.b.JNANatives         ] [shuffle-opensearch] This can result in part of the JVM being swapped out.
[2024-02-28T10:36:25,172][WARN ][o.o.b.JNANatives         ] [shuffle-opensearch] Increase RLIMIT_MEMLOCK, soft limit: 8388608, hard limit: 8388608
[2024-02-28T10:36:25,172][WARN ][o.o.b.JNANatives         ] [shuffle-opensearch] These can be adjusted by modifying /etc/security/limits.conf, for example: 
```

99% of the time we have problems, it's Opensearch. What were the problems you had with the memlock limits in place? These are required, otherwise they wouldn't be there.

**Comment by Farru19** [comment]
When I ran docker compose without commenting memlock limits, it would keep running in loop until I had to stop using ctrl + c. Only to see all other containers runnning expect opensearch was not installed. Anyways I  shifted from lxc containers and created a standlone VM with 2 cores and 8Gs of memory. Everything runs fine now! Problems only occured when using LXC Containers.
