### ISSUE TITLE
dynamic app auth not working

### ISSUE THREAD

**Issue by tbi88** [Shuffle/Shuffle#1350]
**Describe the bug**
The docs state the following for the workflow execution API:

> You can add dynamic app authentication when starting a workflow by using the following header: 'appauth'. Example: 'appauth: jira=auth for jira;elasticsearch=elasticsearch auth'. This works both with the name of the auth, and the ID.

I tried that but it seems not to work.

**To Reproduce**
1. Create a workflow with an app which has some authenticaiton set.
2. run the workflow via the API and set the appauth header.
  --> curl -XPOST -H "Authorization: Bearer secret" https://hostname/api/v1/workflows/6e7dc6cc-6cb9-4c32-98b6-3dddbc6738a8/execute -d '{"execution_argument": "test"}' -k -H "appauth: CrowdStrike=test-auth"

**Expected behavior**
appauth header should overwrite configured authentication in the workflow. Instead the workflow execution is run with the configured authentication. Setting no authentication on the node does also not change the behavior.

**Comment by frikky** [comment]
> **Describe the bug** The docs state the following for the workflow execution API:
> 
> > You can add dynamic app authentication when starting a workflow by using the following header: 'appauth'. Example: 'appauth: jira=auth for jira;elasticsearch=elasticsearch auth'. This works both with the name of the auth, and the ID.
> 
> I tried that but it seems not to work.
> 
> **To Reproduce**
> 
> 1. Create a workflow with an app which has some authenticaiton set.
> 2. run the workflow via the API and set the appauth header.
>    --> curl -XPOST -H "Authorization: Bearer secret" https://hostname/api/v1/workflows/6e7dc6cc-6cb9-4c32-98b6-3dddbc6738a8/execute -d '{"execution_argument": "test"}' -k -H "appauth: CrowdStrike=test-auth"
> 
> **Expected behavior** appauth header should overwrite configured authentication in the workflow. Instead the workflow execution is run with the configured authentication. Setting no authentication on the node does also not change the behavior.

I wonder whether this could be version based. @0x0elliot could you test out whether dynamic app auth works?

**Comment by tbi88** [comment]
I verified this works fine now in the latest nightly backend version for API calls. Curently not working for webhooks...

**Comment by frikky** [comment]
> I verified this works fine now in the latest nightly backend version for API calls. Curently not working for webhooks...

Thanks for the feedback!
