### ISSUE TITLE
changeme is undefined

### ISSUE THREAD

**Issue by mahdidammak2121** [Shuffle/Shuffle#1351]
Hi, can anyone  explain to me why the changeme DB is undefined and there is no options on it
![Screenshot 2024-03-11 143005](https://github.com/Shuffle/Shuffle/assets/117512659/f2103ed5-9263-4697-98b4-ec5924e0bb3e)

**Comment by frikky** [comment]
> Hi, can anyone explain to me why the changeme DB is undefined and there is no options on it ![Screenshot 2024-03-11 143005](https://private-user-images.githubusercontent.com/117512659/311725174-f2103ed5-9263-4697-98b4-ec5924e0bb3e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjc0MTAsIm5iZiI6MTcxMDE2NzExMCwicGF0aCI6Ii8xMTc1MTI2NTkvMzExNzI1MTc0LWYyMTAzZWQ1LTkyNjMtNDY5Ny05OGI0LWVjNTkyNGUwYmIzZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxNDI1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTBmNmRiYTBlY2I2MTZhMDZiMjI2NzcyN2UxNTI3ZjU1YWYyNmExYjk4ZWQxYTEyZDJkOWYwZWVhMmZlYWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UetF_YyIlkxTGiL25oLPMR_Z2S606kRbkSJLRGPy48o)

Change Me is the app in the middle of your screen, not a database. The reason it is undefined is most likely because it hasn't had any value passed through it yet. You can see that when you hoved the part that says "Change Me" that the node in the middle of your screen should light up.

**Comment by mahdidammak2121** [comment]
There was some values that passed through it and it thehive delivers the alerts perfectly but when i try to change the sourceref via changeme it turns out red  
![Screenshot 2024-03-11 153703](https://github.com/Shuffle/Shuffle/assets/117512659/765ad56d-5d58-4ea3-9cc6-22355a34beab)
and i want to change the sourceref via the changeme just like this 
![Capture](https://github.com/Shuffle/Shuffle/assets/117512659/183fb7d0-7f73-49ee-9824-de9c03681d42)

**Comment by frikky** [comment]
What is the current output of the "Change me" node?

**Comment by mahdidammak2121** [comment]
![1](https://github.com/Shuffle/Shuffle/assets/117512659/44ba8777-b4c3-4b7d-ada0-a806cdf1f896)
![Capture](https://github.com/Shuffle/Shuffle/assets/117512659/1f74a350-d28b-41f7-9f7c-6acdb67599da)

**Comment by frikky** [comment]
> ![1](https://private-user-images.githubusercontent.com/117512659/311751227-44ba8777-b4c3-4b7d-ada0-a806cdf1f896.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTUxOTksIm5iZiI6MTcxMDE5NDg5OSwicGF0aCI6Ii8xMTc1MTI2NTkvMzExNzUxMjI3LTQ0YmE4Nzc3LWI0YzMtNGI3ZC1hZGEwLWE4MDZjZGYxZjg5Ni5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMjA4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWJiMzhkOGNiZDVlZTY4YjllNjAxZjhhODNkZDVlNzI0MzMwNGVkZTIzYTM1ODMwYWI4NDEzNTgzMjYwOWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-R6blNfN8P_ASd31ntM825Nr3-1xFrjTbw6iWslJx8) ![Capture](https://private-user-images.githubusercontent.com/117512659/311751244-1f74a350-d28b-41f7-9f7c-6acdb67599da.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTUxOTksIm5iZiI6MTcxMDE5NDg5OSwicGF0aCI6Ii8xMTc1MTI2NTkvMzExNzUxMjQ0LTFmNzRhMzUwLWQyOGItNDFmNy05ZjdjLTZhY2RiNjc1OTlkYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMjA4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzA1NjVmMGU3ZDcwOTM3OThhMWM3M2UxYzg0ZTczNzllMjMxMDlkZGJhNjE4MjkwOWMwYzc2ZjZmZWM1NDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gkqyDrtk7v3TSu4xXeg4iZanrKtF19AvISy_X4t_qhw)

As you can see, the "Result" part is entirely empty.

**Comment by mahdidammak2121** [comment]
Can you please take your time and explain to me why the result is empty but the alerts are showing up in thehive and can you tell what can i do to make the result unemptied  you see that i'm using shuffle fort the 1st time and there is a lot to learn about it

**Comment by frikky** [comment]
> Can you please take your time and explain to me why the result is empty but the alerts are showing up in thehive and can you tell what can i do to make the result unemptied you see that i'm using shuffle fort the 1st time and there is a lot to learn about it

You need to [learn some fundamentals](https://shuffler.io/docs/getting_started) - AKA read documentation/watch videos. Every node that exists doesn't HAVE to do anything. In your case, you are for some reason using "$shuffle_cache" in the "Change me" action (called that because you should change it). $shuffle_cache has no default value unless you actually use our cache (which you don't).

This means that TheHive itself is the only one doing anything, and you have to change the values sent to TheHive to make it make tickets differently.
