### ISSUE TITLE
Implement Data Persistence for Shuffle on Kubernetes using EBS/EFS Provisioners

### ISSUE THREAD

**Issue by cloudifyopsblog** [Shuffle/Shuffle#1363]
**Is your feature request related to a problem? Please describe.**
Our Kubernetes (EKS) cluster currently hosts self-hosted Shuffle, but we encounter challenges in persisting the data and workflows due to the absence of reliable storage solutions. With the current setup utilizing the kubernetes.io/no-provisioner for storage classes, data loss becomes a significant concern in case of node failures or restarts.

**Describe the solution you'd like**
To address this issue effectively, we propose integrating EBS (Elastic Block Store) or EFS (Elastic File System) provisioners within our Kubernetes cluster. Utilizing EBS/EFS provisioners will ensure robust data persistence, mitigating the risk of data loss during node failures or restarts.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shuffle-data
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: Immediate
```

**Key Benefits**

- Enhanced Data Persistence: Integration of EBS/EFS provisioners will enable us to maintain data integrity and continuity even in the face of cluster disruptions.
- Disaster Recovery: With reliable storage solutions in place, we can bolster our disaster recovery capabilities, minimizing downtime and ensuring business continuity.
- Improved Scalability: EBS/EFS provisioners offer scalability features, allowing us to seamlessly accommodate growing data volumes and workload demands.

**Additional context**

- The adoption of EBS/EFS provisioners aligns with industry best practices for data management in Kubernetes environments.
- This enhancement is crucial for ensuring the reliability and resilience of our workflows, thereby enhancing overall system stability and performance.

After changing the provisioner type of the storage class to aws-ebs, the data does not persist as expected. I'm uncertain whether this issue stems from my configuration or potential compatibility issues with Shuffle.

**Comment by frikky** [comment]
@dhaval055 halp please :)

**Comment by cloudifyopsblog** [comment]
We got this working, by making the below changes to the all-in-one deployment file
- We changed the StorageClass provisioner to kubernetes.io/aws-ebs.
- Changing the OpenSearch Kind from Deployment to Statefulset.

**Comment by frikky** [comment]
> We got this working, by making the below changes to the all-in-one deployment file
> 
> * We changed the StorageClass provisioner to kubernetes.io/aws-ebs.
> * Changing the OpenSearch Kind from Deployment to Statefulset.



> We got this working, by making the below changes to the all-in-one deployment file
> 
> * We changed the StorageClass provisioner to kubernetes.io/aws-ebs.
> * Changing the OpenSearch Kind from Deployment to Statefulset.

Thanks for the update!
