### ISSUE TITLE
database elasticsearch

### ISSUE THREAD

**Issue by githubhzj** [Shuffle/Shuffle#1364]
Can OpenSearch, the database of shuffle, be replaced with Elasticsearch?

**Comment by frikky** [comment]
> Can OpenSearch, the database of shuffle, be replaced with Elasticsearch?

Yep! Pretty much the same thing.

**Comment by githubhzj** [comment]
> > Can OpenSearch, the database of shuffle, be replaced with Elasticsearch?
> 
> Yep! Pretty much the same thing.

Now I want to replace it with elasticsearch, how can I do it? thanks

**Comment by frikky** [comment]
> > > Can OpenSearch, the database of shuffle, be replaced with Elasticsearch?
> > 
> > 
> > Yep! Pretty much the same thing.
> 
> Now I want to replace it with elasticsearch, how can I do it? thanks

1. Clone Shuffle as per usual
2. Modify the .env file here (keep OPENSEARCH - pretend it's elasticsearch ;)): https://github.com/Shuffle/Shuffle/blob/c50b84036e386fbc531cf3f40792c8bfb9c2988c/.env#L93

**Comment by githubhzj** [comment]
> > > > Can OpenSearch, the database of shuffle, be replaced with Elasticsearch?
> > > 
> > > 
> > > Yep! Pretty much the same thing.
> > 
> > 
> > Now I want to replace it with elasticsearch, how can I do it? thanks
> 
> 1. Clone Shuffle as per usual
> 2. Modify the .env file here (keep OPENSEARCH - pretend it's elasticsearch ;)): https://github.com/Shuffle/Shuffle/blob/c50b84036e386fbc531cf3f40792c8bfb9c2988c/.env#L93

i tried But failed ,
The following error message is displayed，
[ERROR] Error in initial database connection. Retrying in 5 seconds. the client noticed that the server is not a supported distribution

My configurations:  
# The  docker image version  of elasticsearch  is 8.13.0 , single-node installed
# DATABASE CONFIGURATIONS
DATASTORE_EMULATOR_HOST=shuffle-database:8000
#SHUFFLE_OPENSEARCH_URL=http://shuffle-opensearch:9200
SHUFFLE_OPENSEARCH_URL=https://192.168.253.232:9200
SHUFFLE_OPENSEARCH_USERNAME="elastic"
SHUFFLE_OPENSEARCH_PASSWORD="SWFms8GW4g2*xxxxxx"
SHUFFLE_OPENSEARCH_CERTIFICATE_FILE=
SHUFFLE_OPENSEARCH_APIKEY=
SHUFFLE_OPENSEARCH_CLOUDID=
SHUFFLE_OPENSEARCH_PROXY=
SHUFFLE_OPENSEARCH_INDEX_PREFIX=
SHUFFLE_OPENSEARCH_SKIPSSL_VERIFY=true

**Comment by frikky** [comment]
> > > > > Can OpenSearch, the database of shuffle, be replaced with Elasticsearch?
> > > > 
> > > > 
> > > > Yep! Pretty much the same thing.
> > > 
> > > 
> > > Now I want to replace it with elasticsearch, how can I do it? thanks
> > 
> > 
> > 
> > 1. Clone Shuffle as per usual
> > 2. Modify the .env file here (keep OPENSEARCH - pretend it's elasticsearch ;)): https://github.com/Shuffle/Shuffle/blob/c50b84036e386fbc531cf3f40792c8bfb9c2988c/.env#L93
> 
> i tried But failed , The following error message is displayed， [ERROR] Error in initial database connection. Retrying in 5 seconds. the client noticed that the server is not a supported distribution
> 
> My configurations:
> 
> # The docker image version of elasticsearch is 8.13.0 , single-node installed
> # DATABASE CONFIGURATIONS
> DATASTORE_EMULATOR_HOST=shuffle-database:8000 #SHUFFLE_OPENSEARCH_URL=http://shuffle-opensearch:9200 SHUFFLE_OPENSEARCH_URL=https://192.168.253.232:9200 SHUFFLE_OPENSEARCH_USERNAME="elastic" SHUFFLE_OPENSEARCH_PASSWORD="SWFms8GW4g2*xxxxxx" SHUFFLE_OPENSEARCH_CERTIFICATE_FILE= SHUFFLE_OPENSEARCH_APIKEY= SHUFFLE_OPENSEARCH_CLOUDID= SHUFFLE_OPENSEARCH_PROXY= SHUFFLE_OPENSEARCH_INDEX_PREFIX= SHUFFLE_OPENSEARCH_SKIPSSL_VERIFY=true

Hey!

Are you sure it can connect to 192.168.253.232:9200 inside the docker container of the backend?

**Comment by githubhzj** [comment]
There was no problem with the network connection, I tested multiple ES versions a few days ago and found that 7. X can be replaced normally, but 8.x is not supported。

thanks any more

**Comment by frikky** [comment]
> There was no problem with the network connection, I tested multiple ES versions a few days ago and found that 7. X can be replaced normally, but 8.x is not supported。
> 
> thanks any more

Oh interesting. I'll have a look into it and try to get it fixed - thanks! I'm guessing it has to do with the library we are using.

**Comment by frikky** [comment]
Due to issues with the library, and not wanting a fully new fork (at least right now), we will not be supporting Elasticsearch >= 7.13.0 from now on. 

Tested forking to see if it [was an easy fix](https://github.com/shuffle/opensearch-go/blob/0f7eb6f6cb17cf37d30a594c90f426b55f0c04dc/opensearch.go#L52), but maintaining a downstream library is not worth it.
