### ISSUE TITLE
APP SDK Parsing parameter error

### ISSUE THREAD

**Issue by iifiigii** [Shuffle/Shuffle#1365]
In the [backend/app_sdk/app_base.py] I find a bug.
In line 3702:
"""params[key] = ast.literal_eval(value)"""
AND
In line 124, you define the same name function ast():
def ast(a):
    return ast.literal_eval(str(a))
That make error like:
![image](https://github.com/Shuffle/Shuffle/assets/38291119/11cf99f3-828b-4804-8b2f-42f600221117)

**Comment by frikky** [comment]
> In the [backend/app_sdk/app_base.py] I find a bug. In line 3702: """params[key] = ast.literal_eval(value)""" AND In line 124, you define the same name function ast(): def ast(a): return ast.literal_eval(str(a)) That make error like: ![image](https://private-user-images.githubusercontent.com/38291119/317997019-11cf99f3-828b-4804-8b2f-42f600221117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzQwMTgsIm5iZiI6MTcxMzczMzcxOCwicGF0aCI6Ii8zODI5MTExOS8zMTc5OTcwMTktMTFjZjk5ZjMtODI4Yi00ODA0LThiMmYtNDJmNjAwMjIxMTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIxMDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYTBiYTVlZjBhZWVjMDEyOTRmZDY5NDgzZDYzZjVkYzQwMjNhODQ3YTZkYzM0YzNlZDg5ZWU0MGI4NTQyYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lKd5SozOxSyk4-KSHiTGSv6ThxBHYQ3esjlUnqPAV78)

Nice catch! Thanks for the report. I guess this line hasn't been touched in quite some time, as I haven't seen this problem in ages.

Fixed!
