### ISSUE TITLE
Problem parsing similar variables when names overlap

### ISSUE THREAD

**Issue by kawaiipantsu** [Shuffle/Shuffle#1366]
**Describe the bug**
When you have multiple variables with similar names but still not the same, you can't process/call them very well unless you do it in a order where names go from longest to smallest so that the names never cross or confuses shuffle. It's like it's caching the first variable name it sees and then it wont let you use anything in the same naming convention. Always just sending the first variable names value back.

Version: 1.3.3

**To Reproduce**
Check screenshot.

Make 2 keys that are similar like the following:
test1key = 1234
test1keyname = Hello world

Try to print them out like so:
```
$test1key
$test1keyname
```
The output you get is wrong, well it's really not but there is no way to diiferenciate between variable names. Normally you would be able to put your variable between `$(this.is.my.full.name)` or `${this.is.myfull.name}` and then it would know what part to use and not get confused...
```
1234
1234name
```
...

**Expected behavior**
I would expect to see output like:
```
1234
Hello world
```

**Screenshots**
![image](https://github.com/Shuffle/Shuffle/assets/12233528/552c680a-a28f-4ccb-bc86-ba3cbb0191b5)

```

**Comment by frikky** [comment]
> **Describe the bug** When you have multiple variables with similar names but still not the same, you can't process/call them very well unless you do it in a order where names go from longest to smallest so that the names never cross or confuses shuffle. It's like it's caching the first variable name it sees and then it wont let you use anything in the same naming convention. Always just sending the first variable names value back.
> 
> Version: 1.3.3
> 
> **To Reproduce** Check screenshot.
> 
> Make 2 keys that are similar like the following: test1key = 1234 test1keyname = Hello world
> 
> Try to print them out like so:
> 
> ```
> $test1key
> $test1keyname
> ```
> 
> The output you get is wrong, well it's really not but there is no way to diiferenciate between variable names. Normally you would be able to put your variable between `$(this.is.my.full.name)` or `${this.is.myfull.name}` and then it would know what part to use and not get confused...
> 
> ```
> 1234
> 1234name
> ```
> 
> ...
> 
> **Expected behavior** I would expect to see output like:
> 
> ```
> 1234
> Hello world
> ```
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://private-user-images.githubusercontent.com/12233528/318056726-552c680a-a28f-4ccb-bc86-ba3cbb0191b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzMxODUsIm5iZiI6MTcxMzczMjg4NSwicGF0aCI6Ii8xMjIzMzUyOC8zMTgwNTY3MjYtNTUyYzY4MGEtYTI4Zi00Y2NiLWJjODYtYmEzY2JiMDE5MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIwNTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMDRlMWM4YjJjMGIzMzM2ODg4NWIxM2M0YWY4NDZhNTZlNjhlYjAxOGZkYTE4ZGU0YzJjOGE4ZDkzNWVlMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vc3iNlk2NFtYPoufuslfpjhdrHTy-ko8FIiRWSp8fY0)

Hey!



> **Describe the bug** When you have multiple variables with similar names but still not the same, you can't process/call them very well unless you do it in a order where names go from longest to smallest so that the names never cross or confuses shuffle. It's like it's caching the first variable name it sees and then it wont let you use anything in the same naming convention. Always just sending the first variable names value back.
> 
> Version: 1.3.3
> 
> **To Reproduce** Check screenshot.
> 
> Make 2 keys that are similar like the following: test1key = 1234 test1keyname = Hello world
> 
> Try to print them out like so:
> 
> ```
> $test1key
> $test1keyname
> ```
> 
> The output you get is wrong, well it's really not but there is no way to diiferenciate between variable names. Normally you would be able to put your variable between `$(this.is.my.full.name)` or `${this.is.myfull.name}` and then it would know what part to use and not get confused...
> 
> ```
> 1234
> 1234name
> ```
> 
> ...
> 
> **Expected behavior** I would expect to see output like:
> 
> ```
> 1234
> Hello world
> ```
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://private-user-images.githubusercontent.com/12233528/318056726-552c680a-a28f-4ccb-bc86-ba3cbb0191b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzMxODUsIm5iZiI6MTcxMzczMjg4NSwicGF0aCI6Ii8xMjIzMzUyOC8zMTgwNTY3MjYtNTUyYzY4MGEtYTI4Zi00Y2NiLWJjODYtYmEzY2JiMDE5MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIwNTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMDRlMWM4YjJjMGIzMzM2ODg4NWIxM2M0YWY4NDZhNTZlNjhlYjAxOGZkYTE4ZGU0YzJjOGE4ZDkzNWVlMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vc3iNlk2NFtYPoufuslfpjhdrHTy-ko8FIiRWSp8fY0)

Hey!

Thanks for reporting this - weird how it hasn't been caught before somehow 👀 It also works correctly in our frontend interpreter somehow (JS).

It has to do with the SDK somehow, and it looks to be in this area. Problem should just be the check of an "equals exactly" vs "contains". 

https://github.com/Shuffle/Shuffle/blob/06ac921aa88f004f6e0dff8b2ecc337917ee323e/backend/app_sdk/app_base.py#L2251

**Comment by kawaiipantsu** [comment]
Yes i was wondering how it have not been caught to, but i do believe that has something to do with many run their own "python" code directly in many cases and are not reliant so much on the build in features. But yeah i was building a "template" for a Discord webhook so was doing a lot of output with all my strings and ran into this very much so.

I was concerned that it was a cacheing problem mixup etc.
But i can see in the code that you might be right, it's simply making sure that at first it equals then contain etc.

I hope you get it fixed in the next push, cheers!

**Comment by frikky** [comment]
> Yes i was wondering how it have not been caught to, but i do believe that has something to do with many run their own "python" code directly in many cases and are not reliant so much on the build in features. But yeah i was building a "template" for a Discord webhook so was doing a lot of output with all my strings and ran into this very much so.
> 
> I was concerned that it was a cacheing problem mixup etc. But i can see in the code that you might be right, it's simply making sure that at first it equals then contain etc.
> 
> I hope you get it fixed in the next push, cheers!

I think the only reason it hasn't showed up much is because the autogenerator for names of nodes typically adds a number to everything, meaning they don't at all overlap, and if you type your own names, they are typically very descriptive.

Up to @0x0elliot when it's gonna be fixed ;)

**Comment by frikky** [comment]
Fixed in the latest SDK! It was a problem of using replace(source, dest) instead of replace(source, dest, 1)

Apparently replace() in python does replaceAll by default, without requiring -1
