### ISSUE TITLE
Enable and disable webhooks via API

### ISSUE THREAD

**Issue by githubhzj** [Shuffle/Shuffle#1368]
I refer to docs to test the webhook interface and find some issues:
1. There is no query interface for existing webhooks
2. The output of the stop interface of the webhook is inconsistent with the description
![image](https://github.com/Shuffle/Shuffle/assets/45533210/074606bf-85fb-422c-94b1-63057e9cf8ac)
output below：
![image](https://github.com/Shuffle/Shuffle/assets/45533210/f543048f-3637-4a69-99ad-fbbd89c8a678)

**Comment by satti-hari-krishna-reddy** [comment]
@githubhzj Hey, it looks like there's a mistake in the documentation. The URL provided for deleting webhooks isn't accurate. We'll make sure to fix it. Thanks for bringing it to our attention!

The correct URL for deleting webhooks (on-prem) is:
curl -X DELETE http://<endpoint>:<port>/api/v1/hooks/{webhook_id}/delete -H "Authorization: Bearer APIKEY"

**Comment by satti-hari-krishna-reddy** [comment]
We don't have an endpoint to get a list of  all existing webhooks yet. I'm adding that feature, and it'll be available soon. Once it's ready, i will update the docs : )

**Comment by satti-hari-krishna-reddy** [comment]
Also please make sure to enter the webhook ID without the 'webhook_' prefix. For example 'webhook_19eb8351-7600-4e00...', simply enter '19eb8351-7600-4e00...'

**Comment by githubhzj** [comment]
Ok, thank you  for your reply.
