### ISSUE TITLE
CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by Moetez-Baklouti** [Shuffle/Shuffle#1374]
docker compose installation, problem with opensearch, is there a version for older cpus ?
`shuffle-opensearch | Fatal glibc error: CPU does not support x86-64-v2`
![cpuv2](https://github.com/Shuffle/Shuffle/assets/92986317/aa03bf0c-09cc-4c26-9950-6c673131e8dc)

**Comment by frikky** [comment]
> CPU does not support x86-64-v2

Hey and thanks! This is not something we've seen before.

Which version of Opensearch are you on, and what CPU are you running it on? Please add details about your setup.

**Comment by Moetez-Baklouti** [comment]
I'm using a Ubuntu 23.10 server VM with 4CPU & 8GB RAM
**CPU:**
Architecture:              x86_64
  CPU op-mode(s):     32-bit, 64-bit
  Address sizes:          39 bits physical, 48 bits virtual
  Byte Order:              Little Endian
CPU(s):                       4
  On-line CPU(s) list:   0-3
Vendor ID:                  GenuineIntel
  Model name:            Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Virtualization features:
  Hypervisor vendor:   KVM
  Virtualization type:    full

**Docker Image:** 
opensearchproject/opensearch:2.11.0

I've systematically tested various Docker images from the OpenSearch project on Docker Hub until I found one that met my needs. The chosen image is **opensearchproject/opensearch:2.0.0**

And Shuffle is working perfectly.

**Comment by phr85** [comment]
I had the same issue when setting up via Proxmox.
I had to change the processor type to 'host' for the VM.
