### ISSUE TITLE
shuffle workflow in executing state and pods are in error state

### ISSUE THREAD

**Issue by anjanaradhakrishnan** [Shuffle/Shuffle#1384]
Hi @frikky I'm facing an issue with the shuffle workflow. The shuffle workflow has webhook which is integrated with wazuh and based on the condition it will create case in thhive. Eventhough the case is creating in thhive but the workflow is still in executing state
<img width="214" alt="image" src="https://github.com/Shuffle/Shuffle/assets/105666732/6a192190-e419-4fd3-a61f-61e5f3e6b081">
And the shuffle worker pod is in error state. This is the logs i'm getting 

```
2024/05/10 11:23:29 [DEBUG] Got kubernetes client
2024/05/10 11:23:29 [DEBUG] Created pod "aws-s3-93ced6c7-8638-4178-988e-123456" in namespace "shuffle"
2024/05/10 11:23:30 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Action: Received, Label: 'Upload_file_to_S3', Action: 'AWS S3', Status: SUCCESS, Run status: EXECUTING, Extra=Retry:0
2024/05/10 11:23:30 [WARNING][cd7b9999-bffe-4bc6-b31a-123456] Execution is not executing, but FINISHED. Stopping Transaction update.
2024/05/10 11:23:30 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Shutting down (35)
2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] NEWRESP (from backend): {"success": true, "reason": "success"}
2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Shutdown (FINISHED) started with reason "". Result amount: 4. ResultsSent: 0, Send result:false, Parent: ""
2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Finished shutdown (after 1 seconds).
2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Setting execution to finished because all results are in and it was still in EXECUTING mode. Should set subflow parent result as well (not implemented).
2024/05/10 11:23:31 [INFO][cd7b9999-bffe-4bc6-b31a-123456] Validation. Status: FINISHED, Actions: 4, Extra: 0, Results: 4
2024/05/10 11:23:31 [INFO][cd7b9999-bffe-4bc6-b31a-123456] Already finished (validate)! Stopping the rest of the request for execution.
2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Sending result (set)
```
Here it is showing the  ```Upload_file_to_S3', Action: 'AWS S3', Status: SUCCESS``` but the action is already skipped in the workflow based on the condition.

So if the cases is successfully created  means the workflow should be in success state and the pods should be in completed state right? 
Need your help on this @frikky

**Comment by frikky** [comment]
> Hi @frikky I'm facing an issue with the shuffle workflow. The shuffle workflow has webhook which is integrated with wazuh and based on the condition it will create case in thhive. Eventhough the case is creating in thhive but the workflow is still in executing state <img alt="image" width="214" src="https://private-user-images.githubusercontent.com/105666732/329539545-6a192190-e419-4fd3-a61f-61e5f3e6b081.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjUyODcsIm5iZiI6MTcxNTM2NDk4NywicGF0aCI6Ii8xMDU2NjY3MzIvMzI5NTM5NTQ1LTZhMTkyMTkwLWU0MTktNGZkMy1hNjFmLTYxZTVmM2U2YjA4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxODE2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDg5N2ZlMmMwMzVlY2I4YjNlYTEzOTBkOGRmNzQwYzQ5M2MxZWRlMjQ2MTE3YzI2MzFkOWExNjkwNWJmMWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pw_GuC6PtuydliG0gz14XSODKh9dJ6N1Krt6S7xE1Ww"> And the shuffle worker pod is in error state. This is the logs i'm getting
> 
> ```
> 2024/05/10 11:23:29 [DEBUG] Got kubernetes client
> 2024/05/10 11:23:29 [DEBUG] Created pod "aws-s3-93ced6c7-8638-4178-988e-123456" in namespace "shuffle"
> 2024/05/10 11:23:30 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Action: Received, Label: 'Upload_file_to_S3', Action: 'AWS S3', Status: SUCCESS, Run status: EXECUTING, Extra=Retry:0
> 2024/05/10 11:23:30 [WARNING][cd7b9999-bffe-4bc6-b31a-123456] Execution is not executing, but FINISHED. Stopping Transaction update.
> 2024/05/10 11:23:30 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Shutting down (35)
> 2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] NEWRESP (from backend): {"success": true, "reason": "success"}
> 2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Shutdown (FINISHED) started with reason "". Result amount: 4. ResultsSent: 0, Send result:false, Parent: ""
> 2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Finished shutdown (after 1 seconds).
> 2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Setting execution to finished because all results are in and it was still in EXECUTING mode. Should set subflow parent result as well (not implemented).
> 2024/05/10 11:23:31 [INFO][cd7b9999-bffe-4bc6-b31a-123456] Validation. Status: FINISHED, Actions: 4, Extra: 0, Results: 4
> 2024/05/10 11:23:31 [INFO][cd7b9999-bffe-4bc6-b31a-123456] Already finished (validate)! Stopping the rest of the request for execution.
> 2024/05/10 11:23:31 [DEBUG][cd7b9999-bffe-4bc6-b31a-123456] Sending result (set)
> ```
> 
> Here it is showing the `Upload_file_to_S3', Action: 'AWS S3', Status: SUCCESS` but the action is already skipped in the workflow based on the condition.
> 
> So if the cases is successfully created means the workflow should be in success state and the pods should be in completed state right? Need your help on this @frikky

Hey,

could you find logs for cd7b9999-bffe-4bc6-b31a-123456 on the `shuffle-backend` container around the same time? It looks like the worker that handled the action worked, but the backend may have not updated the state in the database, or it may have not been forwarded properly where it says `Sending result (set)`.

This can be prevented all the time if cache between Workers and the Backend are in place, which it isn't by default. Docker reference for it:

**Comment by frikky** [comment]
https://github.com/Shuffle/Shuffle/blob/06ac921aa88f004f6e0dff8b2ecc337917ee323e/docker-compose.yml#L91

**Comment by shivaniclops** [comment]
Hi @frikky 
As you mentioned we tried out by creating a stateful set for Memcache. Updated env in config map, backend deployment, and orborus deployment. But still some we are getting pod in an error state and we are getting the same error.  I'm not sure why this error pod is getting created. Do we have any other solution for this?

**Comment by shivaniclops** [comment]
``Hi @frikky 
Below are the orborus pod logs

```
2024/05/29 06:02:57 [DEBUG] Starting iteration on environment "Shuffle" (default = Shuffle). Got statuscode 200 from backend on first request
2024/05/29 06:03:45 [INFO] getting running workers in kubernetes
2024/05/29 06:03:45 [DEBUG] using worker image:%!(EXTRA string=ghcr.io/shuffle/shuffle-worker:1.3.1)
2024/05/29 06:03:45 [INFO] Created pod "worker-c629ac24-8ca8-412e-a377-f8dd7f7feeb6" in namespace "shuffle"
2024/05/29 06:06:14 [INFO] getting running workers in kubernetes
2024/05/29 06:06:14 [DEBUG] using worker image:%!(EXTRA string=ghcr.io/shuffle/shuffle-worker:1.3.1)
2024/05/29 06:06:14 [INFO] Created pod "worker-8eae2817-39c1-4774-9054-771b8f092259" in namespace "shuffle"
```

And here is the  worker pod log

```
2024/05/29 08:06:19 [DEBUG] Created pod "shuffle-tools-f57c57af-ff10-44d1-bd7d-1383f6d1b997" in namespace "shuffle"
2024/05/29 08:06:29 [DEBUG][] Action: Received, Label: 'Timestamp_file_creation', Action: 'Shuffle Tools', Status: SUCCESS, Run status: EXECUTING, Extra=Retry:0
2024/05/29 08:06:29 [DEBUG][] Running setexec with status EXECUTING and 3 result(s)
2024/05/29 08:06:29 [INFO][] Inside Decide execution with 3 / 4 results (extra: 0). Status: EXECUTING
2024/05/29 08:06:29 [DEBUG][] Running Upload_file_to_S3  with 1 parents. Names: []string{"1fc05-115-42d3-9c57-2:SUCCESS"}
2024/05/29 08:06:29 [INFO][] Should execute AWS S3:1.0.0 (1fc05-115-42d3-9c57-2) with label Upload_file_to_S3
2024/05/29 08:06:29 [DEBUG][] Action: Send, Label: 'Upload_file_to_S3', Action: 'AWS S3', Run status: EXECUTING, Extra=
2024/05/29 08:06:29 [DEBUG] Got kubernetes client
2024/05/29 08:06:29 [DEBUG] Created pod "aws-s3-22fd-4093-4aaaa1-8d0a-2082" in namespace "shuffle"
2024/05/29 08:06:33 [DEBUG][] Action: Received, Label: 'Upload_file_to_S3', Action: 'AWS S3', Status: SUCCESS, Run status: EXECUTING, Extra=Retry:0
2024/05/29 08:06:33 [WARNING][] Execution is not executing, but FINISHED. Stopping Transaction update.
2024/05/29 08:06:33 [DEBUG][] Shutting down (35)
2024/05/29 08:06:34 [DEBUG][] NEWRESP (from backend): {"success": true, "reason": "success"}
2024/05/29 08:06:34 [DEBUG][] Shutdown (FINISHED) started with reason "". Result amount: 4. ResultsSent: 0, Send result: false, Parent: ""
2024/05/29 08:06:34 [DEBUG][] Finished shutdown (after 1 seconds).
2024/05/29 08:06:34 [DEBUG][] Setting execution to finished because all results are in and it was still in EXECUTING mode. Should set subflow parent result as well (not implemented).
2024/05/29 08:06:34 [INFO][] Validation. Status: FINISHED, Actions: 4, Extra: 0, Results: 4
2024/05/29 08:06:34 [INFO][] Already finished (validate)! Stopping the rest of the request for execution.
2024/05/29 08:06:34 [DEBUG][] Sending result (set)
2024/05/29 08:06:35 [DEBUG][] NEWRESP (from backend): {"success": true}
```
