### ISSUE TITLE
TheHive case creation error

### ISSUE THREAD

**Issue by kiran-k187** [Shuffle/Shuffle#1396]
Hi @frikky , I have integrated the hive with shuffle. Based on the request some of the cases are getting created in the hive. Some cases are in error state (http connection pool error).  Is there any other ways to send the request to shuffle again for creating the cases which are in http connection pool error ?

**Comment by frikky** [comment]
> Hi @frikky , I have integrated the hive with shuffle. Based on the request some of the cases are getting created in the hive. Some cases are in error state (http connection pool error). Is there any other ways to send the request to shuffle again for creating the cases which are in http connection pool error ?

Please don't make multiple issues for the same thing.
