### ISSUE TITLE
Schedule starter can not stop.

### ISSUE THREAD

**Issue by iifiigii** [Shuffle/Shuffle#1400]
**Describe the bug**
I have set up several scheduled tasks and stopped the timers. But I found that these scheduled tasks are still executed repeatedly, even if I delete the timer launcher or delete the workflow. I can't reproduce the problem. 

![image](https://github.com/Shuffle/Shuffle/assets/38291119/75e4d7dd-fb96-4b59-b6ff-d8efdbe064d0)

![image](https://github.com/Shuffle/Shuffle/assets/38291119/8586154b-1206-4564-a757-87187e119ce2)

**Comment by iifiigii** [comment]
Look likes scheduled tasks have stopped. Still don`t know why that scheduled tasks repeat for serval hours after schedule starter stop.

**Comment by frikky** [comment]
> Look likes scheduled tasks have stopped. Still don`t know why that scheduled tasks repeat for serval hours after schedule starter stop.

@satti-hari-krishna-reddy - can you test this please?

**Comment by frikky** [comment]
> Look likes scheduled tasks have stopped. Still don`t know why that scheduled tasks repeat for serval hours after schedule starter stop.

I'm guessing it's because your queue was backed up.

**Comment by iifiigii** [comment]
Sounds reasonable.

For more detail, I check logs:

**Comment by iifiigii** [comment]
Sounds reasonable.

For more detail, I check logs:
1. First, stop the schedule starter.
05-22 11:41:41.437 |   |  
-- | -- | --
2024/05/22 11:41:41 [AUDIT] User admin@****** is accessing workflow b36b*********4579 as admin (stop schedule)
2. Still start workflow every 10 minutes.
05-22 11:47:50.857 |   |  
-- | -- | --
2024/05/22 11:47:50 [INFO][759e********96fa316] Set workflowexecution based on new worker (>0.8.53) for workflow b36b********04579. Actions: 5, Triggers: 0, Results: 5, Status: FINISHED
05-22 11:58:00.847 |   |  
-- | -- | --
2024/05/22 11:57:56 [INFO][7b1*********d3c] Set workflowexecution based on new worker (>0.8.53) for workflow b3********579. Actions: 5, Triggers: 0, Results: 5, Status:
......
3. Until delete workflow:

05-22 13:55:36.346 |   |  
-- | -- | --
2024/05/22 13:55:35 [INFO] User admin@****** is deleting workflow b3*****4579 as admin.

4. The last time of workflow start is 05-22 14:17:55.313
