### ISSUE TITLE
webhook is not working into wazuh integrartion workflow

### ISSUE THREAD

**Issue by floppyG** [Shuffle/Shuffle#1413]
I inserted webhook inside my workflow (shuffle version 1.4.0 onprem deploy) and followed the steps mentioned in [this docuementation](https://wazuh.com/blog/integrating-wazuh-with-shuffle/) and then later following [this video](https://www.youtube.com/watch?v=FBISHA7V15c&t) but it doesn't work, not ingensting any kind of logs, do you have any idea of the problem? of course ask anything inherent to the project and I will be ready to answer you

**To Reproduce**
1. Open/create a workflow
2. insert the webhook node into the workflow
3. follow these steps on this [docs](https://wazuh.com/blog/integrating-wazuh-with-shuffle/)

**Expected behavior**
it should send logs from wazuh into the webook workflow.

**Screenshots**
![image](https://github.com/Shuffle/Shuffle/assets/82391888/2c36f2a2-bed8-482b-909d-9935658da854)

**Comment by frikky** [comment]
> I inserted webhook inside my workflow (shuffle version 1.4.0 onprem deploy) and followed the steps mentioned in [this docuementation](https://wazuh.com/blog/integrating-wazuh-with-shuffle/) and then later following [this video](https://www.youtube.com/watch?v=FBISHA7V15c&t) but it doesn't work, not ingensting any kind of logs, do you have any idea of the problem? of course ask anything inherent to the project and I will be ready to answer you
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open/create a workflow
> 2. insert the webhook node into the workflow
> 3. follow these steps on this [docs](https://wazuh.com/blog/integrating-wazuh-with-shuffle/)
> 
> **Expected behavior** it should send logs from wazuh into the webook workflow.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/82391888/334004514-2c36f2a2-bed8-482b-909d-9935658da854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDkxNjYsIm5iZiI6MTcxNzQwODg2NiwicGF0aCI6Ii84MjM5MTg4OC8zMzQwMDQ1MTQtMmMzNmYyYTItYmVkOC00ODJiLTkwOWQtOTkzNTY1OGRhODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxN2MxOWFmYzdiZWU3NDAzZjc5MzJjMTExYTcwMDcwZWExZjdmMThjMWIzNzAyMDNjNThkN2RhOGNlZmNhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WU2TdMi5WOd492uJ1k5oHa0t6AxzdRsx16eV7Ttbxqw)

Hey! Did you make it work, seeing as you closed this?

**Comment by floppyG** [comment]
Yes, i figured out what was the issue, and found out that was a firewall problem related, not a shuffle problem related at all! 
Mea culpa :/
