### ISSUE TITLE
Infinite application loading time (EXECUTING)

### ISSUE THREAD

**Issue by TIexplorer** [Shuffle/Shuffle#1444]
I'm testing automation of work with the abuseipdb application and have encountered a problem with endless loading.
I tried to use the abuseipdb application on the website shuffler.io, at first it gave the error bad mapping, but then it worked
Docker logs show nothing, meaning errors or warnings
Shuffle is deployed on two servers, everything is fulfilled according to the requirements

2024/07/03 10:52:35 [DEBUG][465138cc-2898-4c51-8b33-e0babb654c93] Action: Send, Label: 'Get IOC', Action: 'AbuseIPDB_v2', Run status: EXECUTING, Extra=
2024/07/03 10:52:35 [DEBUG][465138cc-2898-4c51-8b33-e0babb654c93] Running app get_check_ip in docker NORMALLY as there is no delay set with identifier AbuseIPDB_v2_1-1-0_ff1aa07f-9856-4ec5-9ead-4afc584675f3_465138cc-2898-4c51-8b33-e0babb654c93
2024/07/03 10:52:35 [DEBUG][465138cc-2898-4c51-8b33-e0babb654c93] Container 0f59a9722e28764c2349ab14f6128d791202a4571c7491465134f893744d99e0 was created for AbuseIPDB_v2_1-1-0_ff1aa07f-9856-4ec5-9ead-4afc584675f3_465138cc-2898-4c51-8b33-e0babb654c93
2024/07/03 10:52:35 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Handling DEFAULT execution source default - SKIPPING wait anyway due to exited issues!
2024/07/03 10:52:40 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:52:40 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:52:40 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING
2024/07/03 10:52:45 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:52:45 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:52:45 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING
2024/07/03 10:52:50 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:52:50 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:52:50 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING
2024/07/03 10:52:55 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:52:55 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:52:55 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING
2024/07/03 10:53:00 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:53:00 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:53:00 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING
2024/07/03 10:53:05 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:53:05 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:53:05 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING
2024/07/03 10:53:10 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:53:10 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:53:10 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING
2024/07/03 10:53:15 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Validation. Status: EXECUTING, Actions: 2, Extra: 0, Results: 1
2024/07/03 10:53:15 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] (3) Status: EXECUTING, Results: 1, actions: 2
2024/07/03 10:53:15 [INFO][465138cc-2898-4c51-8b33-e0babb654c93] Inside Decide execution with 1 / 2 results (extra: 0). Status: EXECUTING

shuffle-orborus | 2024/07/03 10:27:24 [INFO][1417cc64-ddc0-45ee-ae3c-1ce475b7379a] New Worker created. Environment Shuffle: docker logs f7e32614e4a6b0c9c049b5d922d28d50d7e08b720edba3b78d01ec7f9af77f9c
shuffle-orborus | 2024/07/03 10:30:45 [INFO] Looking for old containers to remove
shuffle-orborus | 2024/07/03 10:30:45 [INFO] Baseimage: shuffle, Workertimeout: 600
shuffle-orborus | 2024/07/03 10:30:45 [INFO] Should STOP and remove 1 containers.
shuffle-orborus | 2024/07/03 10:30:45 [INFO] Stopping and removing container /worker-9b2623a7-4673-4114-979b-f36e8dff68ce
shuffle-orborus | 2024/07/03 10:30:45 [INFO] Should REMOVE 1 containers.
shuffle-orborus | 2024/07/03 10:41:26 [INFO] Looking for old containers to remove
shuffle-orborus | 2024/07/03 10:41:26 [INFO] Baseimage: shuffle, Workertimeout: 600
shuffle-orborus | 2024/07/03 10:41:26 [INFO] Should STOP and remove 0 containers.
shuffle-orborus | 2024/07/03 10:41:26 [INFO] Should REMOVE 0 containers.

**Comment by TIexplorer** [comment]
I tested the request to abuseipdb using the http application in shuffle and it worked, I suspect there is a bug in the application

**Comment by ScioShield** [comment]
I was going to write a post about trying (and failing) to debug the issue on my laptop (for like 5 hours) and then trying to install it on my main PC where it worked. I had the same issue with the Elasticsearch and VT apps, the only one that worked was the Http one. The fix for me on my laptop was to update with an apt update & upgrade, git pull to get 1.4.1 then critically a "docker system prune -a" to purge the old containers from the system cache. I don't want to speculate on why this worked but it did for me at least. Hope it might work for you !

**Comment by TIexplorer** [comment]
Yep, thank you very much, it really worked
