### ISSUE TITLE
Worker Scale crash - DNS / Docker API

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1472]
Something went wrong with DNS setup in the swarm worker (or Docker CLI): https://github.com/Shuffle/shaffuru/blob/94b5a6587a4c1a81cfa096107743a31fbf4b5423/functions/onprem/worker/worker.go#L1344C1-L1345C1

1. Set up Orborus WITH swarm (latest from July 5th)
2. Run a workflow

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/efcce0a9-aa29-4bcc-b3ee-e5188c4c30ab">

<img width="607" alt="image" src="https://github.com/user-attachments/assets/b1792076-fb88-428a-9899-98976d55afcd">

**Comment by 0x0elliot** [comment]
fixed for proprietary worker.
