### ISSUE TITLE
Subflow --> Startnode coulnd't be found.

### ISSUE THREAD

**Issue by tbi88** [Shuffle/Shuffle#1482]
Hi

I have a workflow which is handling a lot of data, every execution is taking a subset of the data and handling it, then it restarts the workflow with the rest of the data.

<img width="665" alt="image" src="https://github.com/user-attachments/assets/4b85fda9-42be-4ba7-9ee4-3b7cf89f5205">

This works most of the time without any issues. But from time to time I get an error like this:

<img width="463" alt="image" src="https://github.com/user-attachments/assets/4f3a7ce6-354d-4ecd-9ca9-d3037e6ac045">

The process gets stuck when it happens. When I open this execution later and manually rerun it, it works again...

Any idea what could cause this?

Regards

**Comment by frikky** [comment]
Heyo! Sorry for the trouble.

@tbi88 The top part is just looping itself a certain amount of times right? 

@yashsinghcodes - can you write this up for us to figure out over the next week while you are in Subflow-land?

**Comment by tbi88** [comment]
Yes! Basically the "filter-hosts" takes 100 entries from the input list for processing in the bottom nodes. The rest of the list entries are then sent to "restart-workflow".

**Comment by frikky** [comment]
> Yes! Basically the "filter-hosts" takes 100 entries from the input list for processing in the bottom nodes. The rest of the list entries are then sent to "restart-workflow".

I wonder if this is some quirk of how Subflows in Swarm talking to backend is handled. We'll have to test all three:
1. Cloud directly (easiest to test)
2. Without swarm (docker -> backend)
3. With swarm (docker swarm -> backend)

Thanks for the details. These are hard to replicate :(

**Comment by frikky** [comment]
This has been fixed in the latest release of shuffle-shared, and we observed it happen on cloud as well, meaning we had easier testing for it, just more rarely.

We will have a nightly build out with the fix as soon as we can confirm it is working.

**Comment by tbi88** [comment]
Hi,

Updated to the latest nightly yesterday. Again had the issue this night...

<img width="467" alt="image" src="https://github.com/user-attachments/assets/0c01f4f8-be0f-4f7f-885d-2f1d03c15d30">

Regards

**Comment by frikky** [comment]
> Hi,
> 
> Updated to the latest nightly yesterday. Again had the issue this night...
> 
> <img alt="image" width="467" src="https://private-user-images.githubusercontent.com/17710371/358806514-0c01f4f8-be0f-4f7f-885d-2f1d03c15d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODM2OTksIm5iZiI6MTcyMzg4MzM5OSwicGF0aCI6Ii8xNzcxMDM3MS8zNTg4MDY1MTQtMGMwMWY0ZjgtYmUwZi00ZjdmLTg4NWQtMmYxZDAzYzE1ZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDA4Mjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZDU2NWZhMThkZjk0MzViYWEzODUwYmE1MzcwZWQzY2JmMDAzYWZjMGQzYjg0MzRmZjg5ZjcwMzIyN2QwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OSxyUH7FpdxFJMa42PsZa8dTBK2D1ldhWX9_uT_MZ0Y">
> Regards

Thanks for the feedback! This is why we gotta keep testing further, as written in this reply: https://github.com/Shuffle/Shuffle/issues/1482#issuecomment-2274008020

Cloud + Non swarm seems to work. We will set up a specific test for this with 100+ subflow executions in swarm to test reproducability :)

**Comment by tbi88** [comment]
Hey, had a closer look into the issue this weekend. It seems not to be completely random. It always failed around the same time, at the same step and for the same customers. So I changed the starting time for one of the customers, and it failed at the same step. So not related to the time.

But I dont see how it can be related to the input data, since the data was also present in previous steps (which worked fine) and when I rerun the workflow, it actually works...

**Comment by frikky** [comment]
> Hey, had a closer look into the issue this weekend. It seems not to be completely random. It always failed around the same time, at the same step and for the same customers. So I changed the starting time for one of the customers, and it failed at the same step. So not related to the time.
> 
> But I dont see how it can be related to the input data, since the data was also present in previous steps (which worked fine) and when I rerun the workflow, it actually works...

I do suspect it has something to do with the data itself then, even though that doesn't directly make any sense. Workflows that are rerun do run slightly differently, but I don't think that should have too much impact. Can you tell us a bit more about this?
- What time (how many iterations?)
- What step (in the workflow)
- What customers/data?

Don't include anything confidential of course - we just want to see if it has to do with the self-called subflows + special data or not somehow. As an example of how specific it could be, we did find an extreme edgecase on how loops are handled with Subflows + Wait for results just a few weeks ago.

**Comment by tbi88** [comment]
Sure, so basically the input for the workflow is a list of EDR hosts for a customer. The workflow is handling 200 hosts each iteration and restarts itself (with a 20 second delay) with the rest of the hosts. Every host is a JSON with 55 fields.

Customer A: 
- Initially starts at 05:10:54 with 1616 hosts
- 6 iterations without an issue
- 7th iteration fails, basically has 216 hosts left as input, handles 200 of them, and should send 16 to the last run.

Customer B:
- Initially starts at 05:31:30 with 2834 hosts
- 6 iterations without an issue
- 7th iteration fails, 1434 hosts left as input, handles 200 of them, and should send 1234 to the next run.

Looks like another pattern here. I will change the workflow to handle 250 hosts each (instead of 200). Could potentially fix the issue for Customer A. Will see if it helps tomorrow morning.

**Comment by tbi88** [comment]
Ok this is interessting. I just built a very simple test workflow which just increases a number by 10 until the number is >= 100.

<img width="324" alt="image" src="https://github.com/user-attachments/assets/aa55b031-6455-46c5-8d91-70c111339f38">

Exact the same issue. After the first iteration, there are 6 without any issues, and then the 7th failes...

<img width="455" alt="image" src="https://github.com/user-attachments/assets/45f4a8cd-3e75-4df6-9a19-3a7b936c7a27">

**Comment by frikky** [comment]
Thanks for the details! I'll be discussing and building it out with @yashsinghcodes as to have more people be good at subflows

**Comment by tbi88** [comment]
Update this morning. As expected, handling 250 hosts and reducing the iterations solved the issue for Customer A. Customer B still fails with the same pattern since they have more hosts...

**Comment by frikky** [comment]
> Update this morning. As expected, handling 250 hosts and reducing the iterations solved the issue for Customer A. Customer B still fails with the same pattern since they have more hosts...

Thanks for the details! We did make some pretty huge changes yesterday that are now in nightly, but it's not extensively tested yet. It was explicitly tested with User Input and smaller lists + wait for results yesterday, and we'll be trying more today.

**Comment by tbi88** [comment]
just tested this with "ghcr.io/shuffle/shuffle-worker:nightly". Still the same issue.

**Comment by frikky** [comment]
> just tested this with "ghcr.io/shuffle/shuffle-worker:nightly". Still the same issue.

Cheers, thanks for testing!

**Comment by yashsinghcodes** [comment]
> Ok this is interessting. I just built a very simple test workflow which just increases a number by 10 until the number is >= 100.
> 
> <img alt="image" width="324" src="https://private-user-images.githubusercontent.com/17710371/359355056-aa55b031-6455-46c5-8d91-70c111339f38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDEyNDUsIm5iZiI6MTcyOTYwMDk0NSwicGF0aCI6Ii8xNzcxMDM3MS8zNTkzNTUwNTYtYWE1NWIwMzEtNjQ1NS00NmM1LThkOTEtNzBjMTExMzM5ZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEyNDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OTI1Mjk0NDEzMzc1ZjQ3YmJhMDc3MTczMzlhNGNhNWQ4ZTMyZGRmMzlmNzQ4Y2RhNDg1NzRiYjE2Njg3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TaAGTEOjblDUO4MwbleOiRhtavKBgvTQMJbTzbqNeUo">
> Exact the same issue. After the first iteration, there are 6 without any issues, and then the 7th failes...
> 
> <img alt="image" width="455" src="https://private-user-images.githubusercontent.com/17710371/359354892-45f4a8cd-3e75-4df6-9a19-3a7b936c7a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDEyNDUsIm5iZiI6MTcyOTYwMDk0NSwicGF0aCI6Ii8xNzcxMDM3MS8zNTkzNTQ4OTItNDVmNGE4Y2QtM2U3NS00ZGY2LTlhMTktM2E3YjkzNmM3YTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEyNDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YzdhNDk3ZGJlMmY1MzkxNjVlODBkZTY4Y2E5ZDhhOTVhMTY4MWZjMDcxYTc1MTdlNWZhOWE3ZDNiNTNkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B8MkK0-7lJR8Gn1xr98Ertm68h7OJLJ1XCh2HLByVvQ">

Hi @tbi88 if possible can you please share this workflow with me. Would be much easier for me to test and fix :)

**Comment by tbi88** [comment]
Hi @yashsinghcodes 
[test-workflow_copy.json](https://github.com/user-attachments/files/17479733/test-workflow_copy.json)

Here you go, run it with the exec argument of "{"count": 10, "finished": False}".

**Comment by frikky** [comment]
This was fixed a few weeks back and is in nightly already!

**Comment by pschivo** [comment]
Hello there! +1 to this. Doesn't work either with or without Swarm.

**Comment by erjys** [comment]
@frikky @tbi88 @yashsinghcodes @pschivo 
Getting similar incident so Please help me to fix this.  Attaching test workflow for which it is replicating.

<img width="767" height="424" alt="Image" src="https://github.com/user-attachments/assets/4fcacbe9-f901-4faf-be3d-b70d68eddd51" />

**Error on fixed number of execution:**

<img width="1152" height="823" alt="Image" src="https://github.com/user-attachments/assets/c2bc425e-5e49-437a-86b2-fa7cc4bf2ebb" />

**Workflow json file:**

[subflow load testing .json](https://github.com/user-attachments/files/25036702/subflow.load.testing.json)

**Comment by erjys** [comment]
@frikky @tbi88 @yashsinghcodes @pschivo How did you handle this issue ? Please share details.

**Comment by erjys** [comment]
@frikky @tbi88 @yashsinghcodes @pschivo  Found there is fixed SHUFFLE_MAX_EXECUTION_DEPTH as 10 so sub flow stopped after 9th. We can override by setting as environment variable.

<img width="1352" height="673" alt="Image" src="https://github.com/user-attachments/assets/80fa05e3-ab27-4259-9df8-cb47128d827d" />


**Suggestion :** We should return/display improvise meaning full message instead of **"Failed setting workflowexecution: Authorization can't be empty."**
