### ISSUE TITLE
app builder messes up indentation in custom_action function

### ISSUE THREAD

**Issue by tbi88** [Shuffle/Shuffle#1486]
Hi

I added two new actions to an existing app today. After deploying the new build image, the app kept crashing with the error message: 

```
/app # python3 ./app.py
  File "/app/./app.py", line 5124
    if apikey.startswith("Token"):
IndentationError: expected an indented block after 'if' statement on line 5123
```

I reviewed the python code in app.py and saw that there is a "custom_action" function where the indentation is indeed not correct.

```
 def get_search_hosts(self, apikey, url, headers="", queries="", page_size="", query_string="", ssl_verify=False, to_file=False):
        print(f"Started function get_search_hosts")
        params={}
        request_headers={}
        url=f"{url}/api/v2.2/search/hosts"
        ssl_verify = True if str(ssl_verify).lower() == "true" or ssl_verify == "1" else False


        if len(headers) > 0:
            for header in headers.split("\n"):
                if ':' in header:
                    headersplit=header.split(':')
                    request_headers[headersplit[0].strip()] = ':'.join(headersplit[1:]).strip()
                elif '=' in header:
                    headersplit=header.split('=')
                    request_headers[headersplit[0].strip()] = '='.join(headersplit[1:]).strip()
        if apikey != " ":
            if apikey.startswith("Token"):
                request_headers["Authorization"] = apikey
            else:
                apikey = apikey.replace("Token", "", -1).strip()
                request_headers["Authorization"] = f"Token{apikey}"
--
            return request.text

    def custom_action(self, apikey, method="", url="", headers="", queries="", path="", ssl_verify=False, body=""):
        url = self.fix_url(url)

        try:
            method = self.is_valid_method(method)
        except ValueError as e:
            self.logger.error(e)
            return {"error": str(e)}

        if path and not path.startswith('/'):
            path = '/' + path

        url += path

        parsed_headers = self.parse_headers(headers)
        parsed_queries = self.parse_queries(queries)

        if apikey != " ":
    if apikey.startswith("Token"):  <-- Issue starts here -->
        parsed_headers["Authorization"] = apikey
    else:
        apikey = apikey.replace("Token", "", -1).strip()
        parsed_headers["Authoriz**ation"] = f"Token{apikey}"
```

I also find it interessting that I do not have a "custom_action" action defined. So the app builder somehow built that on his own. Even when I removed my added actions, the image was never built again correctly.

So I did fix it manually like this:

```
docker run -it frikky/shuffle:vectra_1.1.0 sh
vi app.py
# fix the code manually
docker commit --change 'CMD ["/bin/sh", "-c", "python app.py --log-level DEBUG"]' 27d695a09894 frikky/shuffle:vectra_1.1.0
docker save frikky/shuffle:vectra_1.1.0 -o vectra.tgz
# transfer vectra.tgz to the worker and load it
```

After that everything started to work again. But as soon as I update the app again it will break again. 

I am pretty sure that we updated the app with 1.4.0 and did not have this issue. Currently running 1.4.2, so probably the bug was introduced in 1.4.1 or 1.4.2.

Here is the app to reproduce the issue. 

[vectra.yaml.zip](https://github.com/user-attachments/files/16531865/vectra.yaml.zip)

Best regards

**Comment by frikky** [comment]
> Hi
> 
> I added two new actions to an existing app today. After deploying the new build image, the app kept crashing with the error message:
> 
> ```
> /app # python3 ./app.py
>   File "/app/./app.py", line 5124
>     if apikey.startswith("Token"):
> IndentationError: expected an indented block after 'if' statement on line 5123
> ```
> 
> I reviewed the python code in app.py and saw that there is a "custom_action" function where the indentation is indeed not correct.
> 
> ```
>  def get_search_hosts(self, apikey, url, headers="", queries="", page_size="", query_string="", ssl_verify=False, to_file=False):
>         print(f"Started function get_search_hosts")
>         params={}
>         request_headers={}
>         url=f"{url}/api/v2.2/search/hosts"
>         ssl_verify = True if str(ssl_verify).lower() == "true" or ssl_verify == "1" else False
> 
> 
>         if len(headers) > 0:
>             for header in headers.split("\n"):
>                 if ':' in header:
>                     headersplit=header.split(':')
>                     request_headers[headersplit[0].strip()] = ':'.join(headersplit[1:]).strip()
>                 elif '=' in header:
>                     headersplit=header.split('=')
>                     request_headers[headersplit[0].strip()] = '='.join(headersplit[1:]).strip()
>         if apikey != " ":
>             if apikey.startswith("Token"):
>                 request_headers["Authorization"] = apikey
>             else:
>                 apikey = apikey.replace("Token", "", -1).strip()
>                 request_headers["Authorization"] = f"Token{apikey}"
> --
>             return request.text
> 
>     def custom_action(self, apikey, method="", url="", headers="", queries="", path="", ssl_verify=False, body=""):
>         url = self.fix_url(url)
> 
>         try:
>             method = self.is_valid_method(method)
>         except ValueError as e:
>             self.logger.error(e)
>             return {"error": str(e)}
> 
>         if path and not path.startswith('/'):
>             path = '/' + path
> 
>         url += path
> 
>         parsed_headers = self.parse_headers(headers)
>         parsed_queries = self.parse_queries(queries)
> 
>         if apikey != " ":
>     if apikey.startswith("Token"):  <-- Issue starts here -->
>         parsed_headers["Authorization"] = apikey
>     else:
>         apikey = apikey.replace("Token", "", -1).strip()
>         parsed_headers["Authoriz**ation"] = f"Token{apikey}"
> ```
> 
> I also find it interessting that I do not have a "custom_action" action defined. So the app builder somehow built that on his own. Even when I removed my added actions, the image was never built again correctly.
> 
> So I did fix it manually like this:
> 
> ```
> docker run -it frikky/shuffle:vectra_1.1.0 sh
> vi app.py
> # fix the code manually
> docker commit --change 'CMD ["/bin/sh", "-c", "python app.py --log-level DEBUG"]' 27d695a09894 frikky/shuffle:vectra_1.1.0
> docker save frikky/shuffle:vectra_1.1.0 -o vectra.tgz
> # transfer vectra.tgz to the worker and load it
> ```
> 
> After that everything started to work again. But as soon as I update the app again it will break again.
> 
> I am pretty sure that we updated the app with 1.4.0 and did not have this issue. Currently running 1.4.2, so probably the bug was introduced in 1.4.1 or 1.4.2.
> 
> Here is the app to reproduce the issue.
> 
> [vectra.yaml.zip](https://github.com/user-attachments/files/16531865/vectra.yaml.zip)
> 
> Best regards

Hey! This indeed should have been fixed, as that was the whole point of the 1.4.2 backend 🤔

PS: The custom_action is an action that allows you to use authentication + custom endpoints in the Workflow itself, instead of relying on building out the app directly. Very helpful in testing. 

@0x0elliot - can you confirm whether this is an issue on 1.4.2 still or not as you got this deployed a while back?

**Comment by frikky** [comment]
Tested all kinds of authentication crossovers. The only one that did NOT work is API-Key + Header/Query + with Prefix, which was somehow missed in the previous tests. Will fix :)

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/b0a66c5e-c186-4957-ac45-290e5d75696b">

**Comment by frikky** [comment]
Two fixes done:
- Auth & Queries now work with Prefixes as expected
- Made the Overwrite functionality work well for Queries & Headers. This means that IF you write the same auth header / query directly in the action, this will overwrite the predefined auth, meaning you as a user have more control for testing. This was not handled the same way everywhere before.

Will add this to the nightly release today.

**Comment by frikky** [comment]
Closing as this should be fixed in nightly. Please re-open it if it didn't solve the problem :)
