### ISSUE TITLE
Incorrect usage of formatting directives, fails in build

### ISSUE THREAD

**Issue by yashsinghcodes** [Shuffle/Shuffle#1492]
I faced the problem while running go test that some of the formatting functions uses incorrect directives which causes it to fail at build and make it not possible to run tests on the files. Here is log from shuffle-backend

```
# shuffle
# [shuffle]
./docker.go:868:4: log.Printf format %s has arg app.Success of wrong type bool
./docker.go:876:4: log.Printf format %s has arg app.Success of wrong type bool
./main.go:2158:3: log.Printf format %s reads arg #1, but call has 0 args
./walkoff.go:409:10: fmt.Sprintf format % C has unknown verb C
./walkoff.go:3977:7: log.Printf format %s reads arg #2, but call has 1 arg
FAIL    shuffle [build failed]
FAIL
```

and here is the logs from shuffle-shared

```
# github.com/shuffle/shuffle-shared
# [github.com/shuffle/shuffle-shared]
./db-connector.go:12676:17: fmt.Sprintf call has arguments but no formatting directives
./files.go:1773:3: log.Println call has possible Printf formatting directive %s
./notifications.go:864:5: log.Printf format %s reads arg #4, but call has 3 args
./notifications.go:930:4: log.Printf format %s reads arg #3, but call has 2 args
./oauth2.go:288:3: log.Println call has possible Printf formatting directive %s
./oauth2.go:484:3: log.Printf format %s reads arg #1, but call has 0 args
./oauth2.go:2562:3: log.Println call has possible Printf formatting directive %s
./oauth2.go:2914:6: log.Println call has possible Printf formatting directive %s
./oauth2.go:3668:3: log.Printf format %#v reads arg #2, but call has 1 arg
./shared.go:1853:6: log.Printf format %s reads arg #2, but call has 1 arg
./shared.go:3724:4: log.Printf format %s has arg trigger of wrong type github.com/shuffle/shuffle-shared.Trigger
./shared.go:7252:7: log.Printf format %s reads arg #1, but call has 0 args
./shared.go:9943:5: log.Printf format %s reads arg #2, but call has 1 arg
./shared.go:10253:3: log.Printf format %s has arg tmpfields.Sharing of wrong type bool
./shared.go:10418:3: log.Printf format %s has arg app.Public of wrong type bool
./shared.go:10557:13: log.Printf call has arguments but no formatting directives
./shared.go:12624:7: log.Printf call needs 3 args but has 4 args
./shared.go:13712:21: fmt.Sprintf format %s has arg newresp.StatusCode of wrong type int
./shared.go:14056:4: log.Printf call needs 1 arg but has 2 args
./shared.go:14062:4: log.Printf call needs 1 arg but has 2 args
./shared.go:14302:4: log.Printf format %d has arg parsedStatus of wrong type float64
./shared.go:15164:18: log.Printf call has arguments but no formatting directives
./shared.go:16829:3: log.Printf format %s reads arg #2, but call has 1 arg
./shared.go:19845:9: log.Printf format %s reads arg #1, but call has 0 args
./shared.go:19920:60: fmt.Sprintf call has arguments but no formatting directives
./shared.go:19926:60: fmt.Sprintf call has arguments but no formatting directives
./shared.go:19932:58: fmt.Sprintf call has arguments but no formatting directives
./shared.go:24151:19: fmt.Sprintf call needs 2 args but has 3 args
./streaming.go:175:3: log.Printf format %s has arg ok of wrong type bool
./db-connector.go:577:24: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./db-connector.go:592:25: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./db-connector.go:7551:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./db-connector.go:7555:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./db-connector.go:7721:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./db-connector.go:7725:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL    github.com/shuffle/shuffle-shared [build failed]
```

shuffle-backend also have some undefine behavior so we do need a refactor in test files to make it sync with current function and usecases.

**Comment by frikky** [comment]
> I faced the problem while running go test that some of the formatting functions uses incorrect directives which causes it to fail at build and make it not possible to run tests on the files. Here is log from shuffle-backend
> 
> ```
> # shuffle
> # [shuffle]
> ./docker.go:868:4: log.Printf format %s has arg app.Success of wrong type bool
> ./docker.go:876:4: log.Printf format %s has arg app.Success of wrong type bool
> ./main.go:2158:3: log.Printf format %s reads arg #1, but call has 0 args
> ./walkoff.go:409:10: fmt.Sprintf format % C has unknown verb C
> ./walkoff.go:3977:7: log.Printf format %s reads arg #2, but call has 1 arg
> FAIL    shuffle [build failed]
> FAIL
> ```
> 
> and here is the logs from shuffle-shared
> 
> ```
> # github.com/shuffle/shuffle-shared
> # [github.com/shuffle/shuffle-shared]
> ./db-connector.go:12676:17: fmt.Sprintf call has arguments but no formatting directives
> ./files.go:1773:3: log.Println call has possible Printf formatting directive %s
> ./notifications.go:864:5: log.Printf format %s reads arg #4, but call has 3 args
> ./notifications.go:930:4: log.Printf format %s reads arg #3, but call has 2 args
> ./oauth2.go:288:3: log.Println call has possible Printf formatting directive %s
> ./oauth2.go:484:3: log.Printf format %s reads arg #1, but call has 0 args
> ./oauth2.go:2562:3: log.Println call has possible Printf formatting directive %s
> ./oauth2.go:2914:6: log.Println call has possible Printf formatting directive %s
> ./oauth2.go:3668:3: log.Printf format %#v reads arg #2, but call has 1 arg
> ./shared.go:1853:6: log.Printf format %s reads arg #2, but call has 1 arg
> ./shared.go:3724:4: log.Printf format %s has arg trigger of wrong type github.com/shuffle/shuffle-shared.Trigger
> ./shared.go:7252:7: log.Printf format %s reads arg #1, but call has 0 args
> ./shared.go:9943:5: log.Printf format %s reads arg #2, but call has 1 arg
> ./shared.go:10253:3: log.Printf format %s has arg tmpfields.Sharing of wrong type bool
> ./shared.go:10418:3: log.Printf format %s has arg app.Public of wrong type bool
> ./shared.go:10557:13: log.Printf call has arguments but no formatting directives
> ./shared.go:12624:7: log.Printf call needs 3 args but has 4 args
> ./shared.go:13712:21: fmt.Sprintf format %s has arg newresp.StatusCode of wrong type int
> ./shared.go:14056:4: log.Printf call needs 1 arg but has 2 args
> ./shared.go:14062:4: log.Printf call needs 1 arg but has 2 args
> ./shared.go:14302:4: log.Printf format %d has arg parsedStatus of wrong type float64
> ./shared.go:15164:18: log.Printf call has arguments but no formatting directives
> ./shared.go:16829:3: log.Printf format %s reads arg #2, but call has 1 arg
> ./shared.go:19845:9: log.Printf format %s reads arg #1, but call has 0 args
> ./shared.go:19920:60: fmt.Sprintf call has arguments but no formatting directives
> ./shared.go:19926:60: fmt.Sprintf call has arguments but no formatting directives
> ./shared.go:19932:58: fmt.Sprintf call has arguments but no formatting directives
> ./shared.go:24151:19: fmt.Sprintf call needs 2 args but has 3 args
> ./streaming.go:175:3: log.Printf format %s has arg ok of wrong type bool
> ./db-connector.go:577:24: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> ./db-connector.go:592:25: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> ./db-connector.go:7551:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> ./db-connector.go:7555:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> ./db-connector.go:7721:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> ./db-connector.go:7725:29: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> FAIL    github.com/shuffle/shuffle-shared [build failed]
> ```
> 
> shuffle-backend also have some undefine behavior so we do need a refactor in test files to make it sync with current function and usecases.

Hola! This sounds like an issue with versions, e.g. if you are on 1.22 or something. Can't you just fix them? Should take like 10 minutes <3
