### ISSUE TITLE
Bug in contains_any_of

### ISSUE THREAD

**Issue by tristandostaler** [Shuffle/Shuffle#1515]
Hello, there is a bug in the following lines:

https://github.com/Shuffle/Shuffle/blob/06ec47a97496440452bcd243ac35dc97c9a0fc5c/backend/app_sdk/app_base.py#L3060-L3063

"," is always contained in ", " so the first if will always be true. The ", " should be the first condition.

**Comment by tristandostaler** [comment]
Also, there is no documentation on it. I found the bug while reading the code to understand how to use "contains_any_of".

**Comment by frikky** [comment]
> Also, there is no documentation on it. I found the bug while reading the code to understand how to use "contains_any_of".

Nice catch, thanks! I don't think this has any meaningful impact due to the strip happening farther down, but fixed it nontheless. 

We do however have a Switchcase/Elif system coming (like we discussed a long time ago) which is being prototyped right now, so I made a hotfix while we're at it :)

![image](https://github.com/user-attachments/assets/33d26e06-017f-4bc4-8c7d-dce3eb88879e)

**Comment by tristandostaler** [comment]
> > Also, there is no documentation on it. I found the bug while reading the code to understand how to use "contains_any_of".
> 
> Nice catch, thanks! I don't think this has any meaningful impact due to the strip happening farther down, but fixed it nontheless.
> 
> We do however have a Switchcase/Elif system coming (like we discussed a long time ago) which is being prototyped right now based on the same system, so I made a hotfix while we're at it :)
> 
> ![image](https://private-user-images.githubusercontent.com/5719530/374638860-33d26e06-017f-4bc4-8c7d-dce3eb88879e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzA5NDQsIm5iZiI6MTcyODUzMDY0NCwicGF0aCI6Ii81NzE5NTMwLzM3NDYzODg2MC0zM2QyNmUwNi0wMTdmLTRiYzQtOGM3ZC1kY2UzZWI4ODg3OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMDMyNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTk0OWRhM2FiZTY4YmQzM2IyYTRiN2EzZDk2MWM2N2FiMDZiYzFkNmFhNzNlY2NjNGY2ZDI4OGY4MmNkY2IxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.V4vRBGMIj8J6xkwXtLSkM7fB_ihoGWbQDPfP4rBor9o)

Really nice! The screenshot seems promising!!
