### ISSUE TITLE
Org & Env name can't be customized

### ISSUE THREAD

**Issue by AppSecAmael** [Shuffle/Shuffle#1540]
**Describe the bug**
If I try to change the values of ORG_ID and ENVIRONMENT_NAME in the .env file before the first startup then Orborus isn't picking up any jobs. 

**To Reproduce**
Create a fresh new environment and set following values in the .env file :
```
ORG_ID=MyCompany
ENVIRONMENT_NAME=Staging
```

Create any new workflow and start it.

**Expected behavior**
Orborus should pick up the jobs.

**Screenshots**

**Comment by frikky** [comment]
> **Describe the bug** If I try to change the values of ORG_ID and ENVIRONMENT_NAME in the .env file before the first startup then Orborus isn't picking up any jobs.
> 
> **To Reproduce** Create a fresh new environment and set following values in the .env file :
> 
> ```
> ORG_ID=MyCompany
> ENVIRONMENT_NAME=Staging
> ```
> 
> Create any new workflow and start it.
> 
> **Expected behavior** Orborus should pick up the jobs.
> 
> **Screenshots** ![execution](https://private-user-images.githubusercontent.com/99711941/383177814-c874cde6-8bf1-45db-9860-fa0861a4e87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTg2OTksIm5iZiI6MTczMDgxODM5OSwicGF0aCI6Ii85OTcxMTk0MS8zODMxNzc4MTQtYzg3NGNkZTYtOGJmMS00NWRiLTk4NjAtZmEwODYxYTRlODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YjhhMjJjYzVhNDU4ZjNjYWZjOGNjMWIwN2IwNjIwMDQ5MzQ4MjA3Zjk1ZjQzYmZjMGRhMzRjZTIxZWIyNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vq3wQLTWOzhFkaXyoJIaY-CGRAjuFCJzd3FoJliUBTE) ![logs](https://private-user-images.githubusercontent.com/99711941/383177838-1aaa4586-2b98-415a-aa61-1b1bcb542943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTg2OTksIm5iZiI6MTczMDgxODM5OSwicGF0aCI6Ii85OTcxMTk0MS8zODMxNzc4MzgtMWFhYTQ1ODYtMmI5OC00MTVhLWFhNjEtMWIxYmNiNTQyOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YzhjYWE0ZjkzODIxYmZhNTA0NDExZWUzOGM5NTkyNzM1YmJkOGUwYzhiODc2MjY0Y2ExMGQzMWIyYWNhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p2l34V_R6aZ74dmKc2gkCDov1Weqtfi6dUr0FHAw-pk)

Hey,

this has to do with default environment variables, and will not be changed. Further: ORG_ID is an ID, or a uuid - not the Org Name. 

In short, what you should do when you are changing default Orborus configurations:
1. Go to /admin?tab=environments
2. Create an environment there
3. Click the copy button on the "command" aprt
4. Run that command on a server

Hope this helps - otherwise reopen the issue :)
