### ISSUE TITLE
Is there any Shuffle app support  block/approval function?

### ISSUE THREAD

**Issue by siriuswhiter** [Shuffle/Shuffle#1557]
Could you please confirm if shuffle has an app that implements the function of blocking workflows? I am trying to integrate shuffle with third-party components. When the workflow reaches a certain node, I need shuffle's workflow to **temporarily block** until the third-party component completes a specific function, and then continue running by **calling back that node**.

I didn't find any app in shuffle that can achieve this function. Is it that such a function doesn't exist or I just haven't found it? Or could you tell me how to create an app with this function, thank you very much.

**Comment by frikky** [comment]
> Could you please confirm if shuffle has an app that implements the function of blocking workflows? I am trying to integrate shuffle with third-party components. When the workflow reaches a certain node, I need shuffle's workflow to **temporarily block** until the third-party component completes a specific function, and then continue running by **calling back that node**.
> 
> I didn't find any app in shuffle that can achieve this function. Is it that such a function doesn't exist or I just haven't found it? Or could you tell me how to create an app with this function, thank you very much.

You found the User Input trigger? :D

**Comment by siriuswhiter** [comment]
> > Could you please confirm if shuffle has an app that implements the function of blocking workflows? I am trying to integrate shuffle with third-party components. When the workflow reaches a certain node, I need shuffle's workflow to **temporarily block** until the third-party component completes a specific function, and then continue running by **calling back that node**.
> > I didn't find any app in shuffle that can achieve this function. Is it that such a function doesn't exist or I just haven't found it? Or could you tell me how to create an app with this function, thank you very much.
> 
> You found the User Input trigger? :D

lol, yeah. Sorry that I didn't read the document in enough detail and misunderstood the function of User Input Trigger at the beginning.
Now I'm looking to see if it's possible to pass more information to the User Input Trigger callback function to make subsequent branch condition decisions, wish me luck 😁.
