### ISSUE TITLE
Authentication in shuffle with ldap or active directory 

### ISSUE THREAD

**Issue by lucyel** [Shuffle/Shuffle#176]
Authentication using ldap or ad along with the native authentication option.

**Comment by frikky** [comment]
Adding more information here from #217

- SAML / SSO
- 2 factor auth
- AD / LDAP

**Comment by frikky** [comment]
More related commits:
https://github.com/frikky/shuffle-shared/commit/8421bbdadaaedeede549d140620d2ed05083316c

https://github.com/frikky/Shuffle/commit/e0aa368b24eaeb3f8550969475a31c46d4f0155e

**Comment by frikky** [comment]
Moving to 1.1 again as it's not a priority for 1.0. Will come back to it as soon as we got customers with the need

**Comment by frikky** [comment]
Seems like AD supports OpenID, so this is solved by extension
