### ISSUE TITLE
Implement custom scrollbars

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#336]
I've given up a couple times by now, but this is really important to make darkmode feel good.

I especially like the middle one here:
http://rommguy.github.io/react-custom-scroll/example/demo.html

Here's an example where it would be amazing help:
![image](https://user-images.githubusercontent.com/5719530/113750940-aa264000-970b-11eb-8c62-d230013df29f.png)

**Comment by arnydo** [comment]
I think the middle example would be a good fit as well.

**Comment by ayush0033** [comment]
Sent PR for 3 pages if it's fine will implement to all other pages like where ever scroll is used.

**Comment by zZedx** [comment]
Hi , is the issue still up ? i would like to work on it.

**Comment by frikky** [comment]
> Hi , is the issue still up ? i would like to work on it.

It indeed still is! Go to any App page and you'll see: https://shuffler.io/apps/outlook_office365
