### ISSUE TITLE
[BUG] Can't use special characters in queries

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#519]
Right now, we have certain limitations for queries in Queries, disallowing special characters and such (see image below). This is due to how these are being parsed into the Python code parameters, which don't allow special characters.

We'll need to find a way to handle all special characters, e.g. by having a very specific translator function which takes all these characters/words and translates them in realtime as they're being sent into Shuffle, while still maintaining the correct name on the frontend.

![image](https://user-images.githubusercontent.com/5719530/134368830-3d0b65f7-0e10-464f-abe7-3de448c33156.png)

**Comment by louismaxx** [comment]
Hello, 

have you managed to find a way to handle the characters ? 
We are trying to look into it on our side but we are a bit lost.

**Comment by frikky** [comment]
> Hello,
> 
> have you managed to find a way to handle the characters ? We are trying to look into it on our side but we are a bit lost.

Hey! Could you send an API example you're trying to do? 

It has to do with Python limitations, and well have to test each part individually

**Comment by louismaxx** [comment]
Hey, 

In our case, we are trying to request Microsoft's Defender For Endpoint API with two filters to grab the alerts created between the datestamp in the filter and the execution of the request. (for example, every alerts in the last 2 minutes).
The second filter expands the response to display more informations in the output.
Example:
` GET https://api-eu.securitycenter.windows.com/api/alerts?$filter=alertCreationTime+ge+2023-02-07T17:10:01.987390Z&$expand=evidence`

I'm available if you need more info. 
In the meantime, I'll try with Graph API to circumvent this issue

**Comment by frikky** [comment]
> $filter

This is fixed in a dev branch now :)

Not just for queries with $, but for literally anything. The major crux was to just translate it into Python code, which is a bit mean about non-letter things.

Anyways, you'll see it working soon!

**Comment by louismaxx** [comment]
Awesome, I'll keep you posted if we have an issue

**Comment by frikky** [comment]
This is solved!
