### ISSUE TITLE
Git clones not using Proxy

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#528]
Whenever a git clone in Shuffle is done, it doesn't use the defined proxies

Make it use them :)

**Comment by kidrek** [comment]
I have the same issue...I'm using a proxy, and the first app downloading don't work.

**Comment by frikky** [comment]
Workaround for getting apps into your system: 
1. In the CLI, manually "git clone https://github.com/Shuffle/python-apps" into the shuffle-apps folder
2. Click "hotload" in the /apps UI

If this doesn't work, [contact us](mailto:support@shuffler.io)

**Comment by frikky** [comment]
Same as #605
