### ISSUE TITLE
Kubernetes Operator: Any chance to create a k8s Operator

### ISSUE THREAD

**Issue by getkub** [Shuffle/Shuffle#584]
**Is your feature request related to a problem? Please describe.**
Lot of organizations run Kubernetes (k8s) as their primary container management and couldn't find a streamlined way to run shuffler in k8s easily.

**Describe the solution you'd like**
The idea is to create a shuffler K8s operator, so the setup can be seamless and professional

**Describe alternatives you've considered**
HELM chart and manual docker conversion to k8s file. Both are point/retrofit solutions 

**Additional context**
Most of the quality products have a K8S operator, which means it is easy to install the product in a seamless/scalable & approved manner

**Comment by frikky** [comment]
Hey!

Shuffle is very dependant on Docker right now, but I know of a lot of users running it in K8s. Problem is we haven't had any customer need for it yet, so it's more of a _want_ than a need. We're focused on getting Docker swarm up and running first, but I see your point.

We do have some pieces underway here, which worked, but aren't optimized at all: https://github.com/frikky/Shuffle/tree/launch/functions/extensions/k8s/shuffle

Please tell me if you'd be willing to help us out with the K8s configuration and testing, and we'd be more than willing to support the entire setup.

**Comment by getkub** [comment]
thanks for the reply. Sure, happy to test Operator and various settings once its done

**Comment by frikky** [comment]
Got Shuffle running on k8s, except for Worker & Orborus. May need to fix App Building as well. Small problems with volumes.

**Comment by frikky** [comment]
Continuation in #970
