### ISSUE TITLE
[Feature] Execution Tab and search.

### ISSUE THREAD

**Issue by azgaviperr** [Shuffle/Shuffle#587]
It would be great to have a single page where we could see execution and be able to filter on it by status. 

Right now we got issue of stall execution and we need to go to each workflow to see it. 

Could be also be great to be able to search in workflow for specific value or keyword. Idea is to see what did happen afor a specific incoming payload.

**Comment by frikky** [comment]
Adding basic search and filter by status may be achievable pretty easy, but making it easy to explore will take some more time.  Setting for 1.1 as observability will be a key aspect to that update :)

**Comment by frikky** [comment]
Will continue this in #657
