### ISSUE TITLE
[BUG] Wait for Result in imported old version workflows

### ISSUE THREAD

**Issue by D4rkw0lv3s** [Shuffle/Shuffle#663]
**Describe the bug**
After importing some workflows from a previous version, if they invoke subflows and the Wait for Results box is checked when the workflows is execute it executes the subflow without any problem and even pass correctly the values but it does not wait for the subflow to end. The main workflows just goes on like the subflow node didn't have the Wait for Results option checked.

If a new main workflows is created, it executes the subflows and the Wait for Results works just fine.

**To Reproduce**
1. Import Old Workflows with a main workflow that calls subflows a use the Wait for Results option;
2. Execute the main workflows;
3. Verify that it does not wait for the results of the subflow.

**Expected behavior**
Wait for the subflow result, without have to create a new main workflow.

**Screenshots**
![image](https://user-images.githubusercontent.com/21691729/148599021-04ab1a01-57f2-40b0-ba3e-196361d7ce0f.png)
![image](https://user-images.githubusercontent.com/21691729/148599174-c14dbee3-6a82-42b4-b0ae-abc78ec8be99.png)
![image](https://user-images.githubusercontent.com/21691729/148599239-73e608bb-42a3-49ee-98b1-d532318c03d9.png)

The next nodes fail because they don't get the result from the previous node (the subflow execution node).

**Comment by frikky** [comment]
Found this in the backlog. It was fixed a while back :)
