### ISSUE TITLE
Enable search of all apps in workflow, and auto-enabling when using

### ISSUE THREAD

**Issue by 219liangyi** [Shuffle/Shuffle#675]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/19781251/149096963-a32a7cb8-fb0a-4ae4-893f-d991d78db07d.png">
<img width="525" alt="image" src="https://user-images.githubusercontent.com/19781251/149097026-d5d6059f-4ddd-4343-9838-ef5bd8675d8a.png">

**Comment by frikky** [comment]
Hey! You'll have to activate it first, which will also build the Docker container. Right now, these aren't built by default, as that would make it into 300+ apps that are kind of useless.

How about we add them to the list in a workflow as well, so you can find them, but when you try to add them, we make a disclaimer that it should be built first? Or even better: autobuild when you try to use it? :thinking:

**Comment by 219liangyi** [comment]
auto build I think it's a very good user experience

**Comment by frikky** [comment]
> auto build I think it's a very good user experience

Indeed - thanks for the suggestion! :star_struck:

**Comment by frikky** [comment]
Related to #657
