### ISSUE TITLE
[Bug] Error when trying to implement SSO with Keycloak

### ISSUE THREAD

**Issue by DavidtheGoliath** [Shuffle/Shuffle#700]
**Describe the bug**
I get `{"success": false, "reason": "Failed XML unpacking in SAML"}` when I'm supposed to be redirected into the login page whilst using Keycloak for SSO.

**To Reproduce**
Setup for SSO using Keycloak.

**Expected behavior**
To be logged in and redirected into my shuffle org

**Screenshots**

What I get in my browser

![01 02 2022_08 01 26_REC](https://user-images.githubusercontent.com/31187099/151916182-a4f626e9-0683-4e07-89e3-2656fffbd9f0.png)

What I get in the logs

![01 02 2022_08 07 57_REC](https://user-images.githubusercontent.com/31187099/151916289-f447b0b6-923b-47ed-925b-7c83543c29c8.png)

** Debug logs (NOT APPLICABLE FOR CLOUD)**
Run the following commands and paste them
```
docker logs shuffle-backend
docker ps -a
```

**Comment by frikky** [comment]
As discussed, this turned out to be due to sending an AuthnRequest instead of SAMLResponse. We don't support the former yet, as it's supposed to be sent from Shuffle to the IdP (KeyCloak) to handle requests.

Turn that off in the config. We'll add this to the docs, no? ;)

**Comment by DavidtheGoliath** [comment]
Yes please. Most definitely.

**Comment by frikky** [comment]
> Yes please. Most definitely.

As discussed yesterday: KeyCloak was most likely configured badly, so the AuthnRequest we see was actually an attempt to use Shuffle as the Identity provider, which in reality should be Keycloak. This should all work out with OpenID tho (TBD today!), as Shuffle doesn't properly support SAML v2.0 yet.

**Comment by frikky** [comment]
Closing as this has been solved with OpenID - we probably won't implement SAML v2.0 anytime soon.
