### ISSUE TITLE
Add file download location to downloading file in shuffle tools

### ISSUE THREAD

**Issue by hanneswille** [Shuffle/Shuffle#759]
When using the action Download remote file in shuffle tools, the file is always stored in the shuffle-files/ directory. Because many tools like execute bash run in the docker itself, it makes it complex to utilise downloaded files.

It would be ideal to have the option to specify if the file would be downloaded in the docker container or outside, because both have valid uses.

**Comment by frikky** [comment]
In short; there's no way to save outside docker, as that's the point of containers.

A good way to do this instead is to add another folder to the docker-compose mounting point and use that as the default folder. 

How would you want to utilise the downloaded files?
