### ISSUE TITLE
Supper OpenID Connect with AND without PKCE

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#790]
Client Secret vs no Client Secret (with challenge)

Check benefits, and choose one / add a way to select by the user

**Comment by khalavak** [comment]
Hello, what is the timeframe for this enhancement getting implemented?

**Comment by frikky** [comment]
> Hello, what is the timeframe for this enhancement getting implemented?

In the next few weeks is the goal, but it's not been planned for implementation yet. I'm out traveling right now and can't push it through as soon as I hoped sadly

**Comment by frikky** [comment]
@khalavak this has now been implemented as of Shuffle version 1.0.2 (nightly). Closing :+1: 

[Documentation with an example for Azure AD](http://shuffler.io/docs/extensions#azure_ad)
