### ISSUE TITLE
There are many such scenarios in the project. After an app is completed, I need to go through a period of time, which may be 1 day or 3 days, before I go to the next step.

### ISSUE THREAD

**Issue by 219liangyi** [Shuffle/Shuffle#813]
There are many such scenarios in the project. After an app is completed, I need to go through a period of time, which may be 1 day or 3 days, before I go to the next step.
Do you have such a scene? Execute the next step after the specified time

**Comment by frikky** [comment]
Check the "delay" in the top right of each app, next to where you can edit the name :+1:

**Comment by 219liangyi** [comment]
Thank you.
