### ISSUE TITLE
[Feature Request] ADD an External URL environment parameter

### ISSUE THREAD

**Issue by azgaviperr** [Shuffle/Shuffle#829]
Currently we have a  BASE_URL parameter and this one is use for internal component of Shuffle. 

In the case of OpenID/SSO setup we need to change it accordingly to redirect properly the request. However this parameter change could lead to different issues. 

It should be preferred to have another parameter for EXTERNAL_URL Parameter.

**Comment by frikky** [comment]
This was added, mainly for OpenID/SSO a while back:

```
SSO_REDIRECT_URL=http://localhost:3001
```
