### ISSUE TITLE
I can't pass in parameters when using webhook. I hope webhook can pass parameters, which is very important to me

### ISSUE THREAD

**Issue by 219liangyi** [Shuffle/Shuffle#835]
I can't pass in parameters when using webhook. I hope webhook can pass parameters, which is very important to me

**Comment by frikky** [comment]
What is an example URL you're trying?

In general, parameters are parsed as JSON in Shuffle's execution argument. This is because we don't regard the parameters directly.

**Comment by 219liangyi** [comment]
https://xx.com/api/v1/hooks/webhook_294fba88-aee7-42ab-b5d5-a8dea37e52b/33  or  {"id":33}
The external triggers the workflow through webhook and passes the parameters to the next execution parameter. Otherwise, I don't know which data is being executed

**Comment by frikky** [comment]
> https://xx.com/api/v1/hooks/webhook_294fba88-aee7-42ab-b5d5-a8dea37e52b/33 or {"id":33} The external triggers the workflow through webhook and passes the parameters to the next execution parameter. Otherwise, I don't know which data is being executed

You can't add a path to it on the end, e.g. /33 - it only works with a body (POST) or queries (POST / GET). If you need the e.g. /33, please show us a full example with the source system :) 

It has to be something like https://xx.com/api/v1/hooks/webhook_294fba88-aee7-42ab-b5d5-a8dea37e52b?id=33

**Comment by 219liangyi** [comment]
https://xx.com/api/v1/hooks/webhook_294fba88-aee7-42ab-b5d5-a8dea37e52b?id=33 This also meets my needs very much. When my work order system creates a work order, I call this webhook once to generate a workflow.
At present, the system does not support obtaining the value of webhook id. I hope to support it

**Comment by frikky** [comment]
> https://xx.com/api/v1/hooks/webhook_294fba88-aee7-42ab-b5d5-a8dea37e52b?id=33 This also meets my needs very much. When my work order system creates a work order, I call this webhook once to generate a workflow. At present, the system does not support obtaining the value of webhook id. I hope to support it

Did you upgrade to the latest version? The id=33 will become {"id": 33} in Shuffle, and e.g. id=33&name=test will become {"id": 33, "name": "test"}

Please try on shuffler.io with a sample workflow to see it in action :)

**Comment by 219liangyi** [comment]
Very good. I'm done
