### ISSUE TITLE
JSON with Dots in Key Name

### ISSUE THREAD

**Issue by ChestoOfGlen** [Shuffle/Shuffle#848]
**Describe the bug**
JSON that includes dots (.) in the key name is not being appropriately handled by Shuffle when attempting to reference a key using the "dot notation" syntax used by Shuffle.

**To Reproduce**
1. Create a workflow to repeat back "$exec._source.kibana.alert.rule.name" using the Shuffle Tools
2. Put the following JSON into the Execution Argument 
`{"_index": ".internal.alerts-security.alerts-default-000001", "_id": "123456789", "_score": 1.0, "_source": {"kibana.version": "8.1.2", "kibana.alert.rule.category": "Threshold Rule", "kibana.alert.rule.consumer": "siem", "kibana.alert.rule.execution.uuid": "987654321", "kibana.alert.rule.name": "Agent Spoofing - Multiple Hosts Using Same Agent", "kibana.alert.rule.producer": "siem", "kibana.alert.rule.rule_type_id": "siem.thresholdRule", "kibana.alert.rule.uuid": "abcde12345"}}`
3. Click the test execution button
4. The return from the repeater will be empty as it is interpreting it as a key many levels deep `[exec][_source][kibana][alert][rule][name]` instead of what it should be `[exec][_source][kibana.alert.rule.name]`

**Expected behavior**
The repeat back to me should return the rule name, which is "Agent Spoofing - Multiple Hosts Using Same Agent"

**Screenshots**
![image](https://user-images.githubusercontent.com/37160206/167523573-40814984-339f-4f01-ab7a-21d906472d25.png)
![image](https://user-images.githubusercontent.com/37160206/167523586-84b58531-1b3e-4e21-ac19-758fcfca7671.png)
![image](https://user-images.githubusercontent.com/37160206/167523600-2e5e812e-0179-4427-ad86-f3156b0c5485.png)

**Comment by frikky** [comment]
Hey! There is indeed a problem with dot notation, but thankfully we have Liquid to the rescue. It makes things more complicated, but allows us to do pretty much anything with python. Here's a way to grab the "kibana.alert.rule.consumer" from it in a single line.

`{% python %}import json; print(json.loads('$exec._source')["kibana.alert.rule.consumer"]){% endpython %}`

We won't fix this until we got a proper workaround which replaces all the body's data appropriately, but this kind of data tampering makes it hard to work with certain documentation so is kept out of scope for now. 

Hope this allows you to keep pushing with Kibana :+1:

**Comment by frikky** [comment]
Update: This has been solved in its entirety. These keys can be used the same as any other keys.
