### ISSUE TITLE
Inconsistent Replacing of Dots with Underscores in JSON Exec Argument

### ISSUE THREAD

**Issue by ChestoOfGlen** [Shuffle/Shuffle#849]
**Describe the bug**
It appears that there may be some inconsistent replacing of dots (.) in JSON data with underscores (_) for data coming in via webhook.

**To Reproduce**
1. Create a workflow with repeat back to me for $exec. Add a webhook trigger.
2. Run the below Python script (install requests and urllib3 using pip, and update the `shuffle_webhook_url` var to your webhook URL)
3. Observe that the `alert` variable contains `kibana.version` within `_source` in the Python script, but the exec argument in Shuffle has `kibana_version`

**Expected behavior**
That replacement of dots with underscores in key names should be consistent, either to do none of them or to do all of them. 
This may be related to [this issue I raised for handling JSON keys with dots in their names](https://github.com/Shuffle/Shuffle/issues/848).

**Screenshots**
![image](https://user-images.githubusercontent.com/37160206/167525908-18fe87a3-11d9-4e66-a5d2-69332aaa7de5.png)
![image](https://user-images.githubusercontent.com/37160206/167525918-d4c6a70a-5a19-4ab5-9205-dfaafedb3d19.png)

```
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning) #Suppress insecure cert warnings

def api_post(api, header, path, jsondata):
    req_post = requests.post(api + path, headers=header, json=jsondata, verify=False)
    return req_post.json()

shuffle_webhook_url = "https://<WEBHOOK-URL-GOES-HERE>"
shuffle_api_headers = {
    "Accept": "application/json",    
    "Content-Type": "application/json"
    }

alert = {"_index": ".internal.alerts-security.alerts-default-000001", "_id": "123456789", "_score": 1.0, "_source": {"kibana.version": "8.1.2", "kibana.alert.rule.category": "Threshold Rule", "kibana.alert.rule.consumer": "siem", "kibana.alert.rule.execution.uuid": "987654321", "kibana.alert.rule.name": "Agent Spoofing - Multiple Hosts Using Same Agent", "kibana.alert.rule.producer": "siem", "kibana.alert.rule.rule_type_id": "siem.thresholdRule", "kibana.alert.rule.uuid": "abcde12345"}}
print(alert)
send_to_shuffle_webhook = api_post(shuffle_webhook_url, shuffle_api_headers, '', alert)
print(send_to_shuffle_webhook)
```

**Comment by frikky** [comment]
Thanks! I was under the impression this half-built feature was turned off entirely for now, but apparently not. Will have to get that sorted, and may indeed in the future use it with replacements entirely

**Comment by frikky** [comment]
Verified and fixed! Next versions won't have this problem. The replacement is disabled entirely for now
