### ISSUE TITLE
Workflow content formatting

### ISSUE THREAD

**Issue by 219liangyi** [Shuffle/Shuffle#856]
This is a workflow created in my daily work. Its readability is poor. I expect it to be formatted like the following.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/19781251/168479583-3bfb7f6c-9a0f-4677-a04e-d5005688c25c.png">
Activiti's is easy to understand
<img width="427" alt="image" src="https://user-images.githubusercontent.com/19781251/168479536-12fbdfaf-50f6-4837-b849-8a5ac1e2136a.png">

**Comment by frikky** [comment]
If just for readability, we've made some ways you can build like that in Shuffle too. Have a look:
**Initial**
![image](https://user-images.githubusercontent.com/5719530/168598438-fd978902-fe85-48c0-8cce-0fd390fa0fe1.png)

**Initial Formatting**
![image](https://user-images.githubusercontent.com/5719530/168598797-c851f259-41c8-4110-ad06-06c3f1865a3e.png)

In short:
- You can hide small pieces that are just there for formatting
- You can make straight lines if you want to
- You can add comments to highlight areas with color and text

I agree we have to make it better, but it's all up to you to make it good. What exactly would help you? We've thought about a "formatting button" which does this for you

PS: I think Activiti looks really bad (:

**Comment by 219liangyi** [comment]
Thank you. The formatting effect is very good. I look forward to it，
ps:I don't like activiti either
