### ISSUE TITLE
Parse IOCs action doesn't work in cloud

### ISSUE THREAD

**Issue by DavidtheGoliath** [Shuffle/Shuffle#865]
**Describe the bug**
I'm working on a workflow and the Parse IOC's action for the Shuffle tools does not work as needed, once I get to this step it just loads but nothing happens. No results given back and no indication that the node/execution ran or otherwise.
 
**To Reproduce**
1. Get an Email into Shuffle
2. Select the body of the email
3. Try parsing out the IOC's from your email...

**Expected behavior**
A result should be gotten  but in our case the execution doesn't stop running

**Screenshots**

** Debug logs (NOT APPLICABLE FOR CLOUD)**
Run the following commands and paste them
```
docker logs shuffle-backend
docker ps -a
```

**Comment by frikky** [comment]
Fixed
