### ISSUE TITLE
Mobile site moves up and down due to the changing text

### ISSUE THREAD

**Issue by adamyuu** [Shuffle/Shuffle#866]
https://user-images.githubusercontent.com/60894651/170093234-0906c556-3841-4b10-90c5-8db89948fdc2.MOV

When the changing text at the top of the mobile page rotates to a text that is big enough to wrap into the next line it moves the entire webpage up and down.

I’m not sure what’s causing this exactly but try checking the divider’s height or width so that there’s enough space without having to push down the other dividers.

**Comment by frikky** [comment]
Ok that's annoying - thanks!

**Comment by frikky** [comment]
@ayush0033 when you start the next work on the mobile optimization, please handle this too!
