### ISSUE TITLE
AzureAD SSO - Bad ID Token Error

### ISSUE THREAD

**Issue by ChestoOfGlen** [Shuffle/Shuffle#885]
**Describe the bug**
I have configured OpenID authentication with Azure as per the documentation: https://shuffler.io/docs/extensions#azure_ad
I am getting an error `{"success": false, "reason": "Bad ID token provided"}` whenever I try to use the login via SSO button.

**To Reproduce**
1. Setup Shuffle for OpenID Auth via Azure
2. Try to use the login via SSO button

**Screenshots**
My OpenID configuration is as per this screenshot
![image](https://user-images.githubusercontent.com/37160206/174970520-426e6efb-18f7-49bd-8384-b0ca188a2d97.png)

Granted permissions for the Azure app (I note that the first time I tried to use SSO is requested the openid permission so I just added it directly to the grants for the app).
![image](https://user-images.githubusercontent.com/37160206/174972244-c37a6c56-0dac-4096-be7e-49804c446bd1.png)

**Debug logs**
My relevant backend container logs are as below (some of the base64 data has been truncated)
```
2022/06/22 07:33:39 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpXXXXXXXXXXXXXXXX
2022/06/22 07:33:39 [WARNING] Couldn't find AUD - continuing to next: {"typ":"JWT","alg":"RS256","kid":"jS1Xo1OWDj_52vbwGNgvQO2VzMc"}
2022/06/22 07:33:39 eyJhdWQiOiI2M2VkYzUzMi0wODhkLTRXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2022/06/22 07:33:39 [WARNING] Failed base64 decode of state (2): illegal base64 data at input byte 1003
2022/06/22 07:33:39 pF_HSIuq4t9il3Wp7qeWZclvXPfMgtAzlA3XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2022/06/22 07:33:39 [WARNING] Failed base64 decode of state (2): illegal base64 data at input byte 2
2022/06/22 07:33:39 [ERROR] Bad ID token provided: Couldn't verify nonce
2022/06/22 07:33:39 http: superfluous response.WriteHeader call from github.com/shuffle/shuffle-shared.HandleOpenId (shared.go:11542)
```

I've tried both using the v2.0 and 1.0 OAuth API's as per this semi-related issue https://github.com/Shuffle/Shuffle/issues/883 which does not seem to have had any effect.
Currently running the frontend and backend containers on 1.0.2, but I was also testing using the "nightly" tag, again without any noticeable change.

**Comment by frikky** [comment]
I know of a few successful configurations of OpenID with Azure, but there's usually some initial trouble. 

Thanks, we'll have to get back in there and test it out again ourselves, or we could have a support call to dig into it

**Comment by ChestoOfGlen** [comment]
Apologies its taken me so long to get back to this.
I've had another quick look at this and have got a bit further with it.

When I set the BASE_URL to our public URL and port 5001 then the SSO authentication works, however the redirect after login goes to https://public-url.com:5001 which returns a 404 as the page doesn't exist on the backend container (which is expected).
I can then just remove the port from the URL and then I am successfully logged in using SSO. But obviously that is not ideal.

I have our UAT Shuffle instance published behind a reverse proxy (HAProxy), which has the following paraphrased logic:
If SHUFFLE_UAT URL and PORT 5001 = Send to Webserver VM on port 5001 (HTTP) for Backend container
If SHUFFLE_UAT URL = Send to Webserver VM on port 3443 (HTTPS) for Frontend container

I'm not exactly familiar with how the API calls are handed off between the frontend and backend, but obviously there's something in there.

I'm happy to have a support call to dig further into it if we still need it.

**Comment by frikky** [comment]
> Apologies its taken me so long to get back to this. I've had another quick look at this and have got a bit further with it.
> 
> When I set the BASE_URL to our public URL and port 5001 then the SSO authentication works, however the redirect after login goes to https://public-url.com:5001 which returns a 404 as the page doesn't exist on the backend container (which is expected). I can then just remove the port from the URL and then I am successfully logged in using SSO. But obviously that is not ideal.
> 
> I have our UAT Shuffle instance published behind a reverse proxy (HAProxy), which has the following paraphrased logic: If SHUFFLE_UAT URL and PORT 5001 = Send to Webserver VM on port 5001 (HTTP) for Backend container If SHUFFLE_UAT URL = Send to Webserver VM on port 3443 (HTTPS) for Frontend container
> 
> I'm not exactly familiar with how the API calls are handed off between the frontend and backend, but obviously there's something in there.
> 
> I'm happy to have a support call to dig further into it if we still need it.

Hey there! We've released a new version that uses it's own SSO url to redirect to the correct place. You can see it here in the docs at the same place - please update and try it out! There were some problems with BASE_URL being overwritten hence we made the change.

SSO_REDIRECT_URL=http://<URL>:<PORT>

https://shuffler.io/docs/extensions#single_signon_sso

**Comment by ChestoOfGlen** [comment]
Hey Frikky, apologies forgot to mention that I also had SSO_REDIRECT_URL set in my .env file during my test, but it didn't seem to have any effect. I'd forgotten about it because I saw Mezcal mention it wasn't working for them either in Discord.

I've tested again with the following vars set (this UAT instance is all on a single VM) and on the latest nightly version:
BASE_URL=http://shuffle-backend:5001
SSO_REDIRECT_URL=https://public.example.com

And there seems to be no change. When I try to login using SSO Microsoft complains that "http://shuffle-backend:5001/api/v1/login_openid" doesn't match the redirect URI's in my app (which is true and expected).

If I set BASE_URL=https://public.example.com:5001 then the SSO sign-in works but we're back to the above issue of not getting redirected to the frontend and ending up at https://public.example.com:5001

I can only conclude (at least in my environment) that SSO_REDIRECT_URL is not working.

**Comment by frikky** [comment]
Thanks @ChestoOfGlen! 

Will do more testing and get it pushed out into latest when it's working

**Comment by frikky** [comment]
> Just chiming in and commenting to follow the issue - we're also having the same error :)

Hey! @ChestoOfGlen and @bvirgilioamnh

We have a new release candidate out for version 1.1.0 of Shuffle which has the problem solved. You can get them by using the packages found here: https://github.com/orgs/Shuffle/packages?repo_name=Shuffle

Example for frontend: 
```
docker pull ghcr.io/shuffle/shuffle-frontend:1.1.0
```

Update docs: https://shuffler.io/docs/configuration#updating_shuffle

**Comment by bvirgilioamnh** [comment]
I think we're still running into the same issue.

Process:
Click SSO, redirects to Azure AD, sign in, Redirects to frontend on /api/v1/login_openid with below error:
{"success": false, "reason": "Bad ID token provided"}

```
 Shuffle]$ sudo docker compose images
Container            Repository                         Tag                 Image Id            Size
shuffle-backend      ghcr.io/shuffle/shuffle-backend    1.1.0               fe6a8f517969        54.1MB
shuffle-frontend     ghcr.io/shuffle/shuffle-frontend   1.1.0               df880c8858e5        190MB
shuffle-opensearch   opensearchproject/opensearch       1.2.4               6842d435e62e        827MB
```

Redacted (example.com = internal domain) logs

```shuffle-backend     | 2022/11/18 18:54:09 [INFO] INITIAL Api authentication failed in notification list: Missing authentication
shuffle-backend     | 2022/11/18 18:54:09 [WARNING] Api authentication failed in handleInfo: Missing authentication
shuffle-backend     | 2022/11/18 18:54:09 [INFO] INITIAL Api authentication failed in notification list: Missing authentication
shuffle-backend     | 2022/11/18 18:54:09 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
shuffle-backend     | 2022/11/18 18:54:09 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
shuffle-backend     | 2022/11/18 18:54:09 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
shuffle-backend     | 2022/11/18 18:54:09 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
shuffle-backend     | 2022/11/18 18:54:09 [INFO] INITIAL Api authentication failed in notification list: Missing authentication
shuffle-backend     | 2022/11/18 18:54:09 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
shuffle-backend     | 2022/11/18 18:54:09 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
shuffle-backend     | 2022/11/18 18:54:09 [INFO] INITIAL Api authentication failed in notification list: Missing authentication
shuffle-backend     | 2022/11/18 18:54:09 [WARNING] Api authentication failed in handleInfo: Missing authentication
shuffle-backend     | 2022/11/18 18:54:10 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
shuffle-backend     | 2022/11/18 18:54:10 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
shuffle-backend     | 2022/11/18 18:54:49 eyJ0e***REDACTED****SSJ9
shuffle-backend     | 2022/11/18 18:54:49 [WARNING] Couldn't find AUD - continuing to next: {"typ":"JWT","alg":"RS256","kid":"2ZQpJ3UpbjAYXYGaXEJl8lV0TOI"}
shuffle-backend     | 2022/11/18 18:54:49 eyJh***REDACTED****iOiIyLjAifQ
shuffle-backend     | 2022/11/18 18:54:49 [WARNING] Failed base64 decode of state (2): illegal base64 data at input byte 971
shuffle-backend     | 2022/11/18 18:54:49 rk9Pb0***REDACTED****Pd2hw
shuffle-backend     | 2022/11/18 18:54:49 [WARNING] Failed base64 decode of state (2): illegal base64 data at input byte 13
shuffle-backend     | 2022/11/18 18:54:49 [ERROR] Bad ID token provided: Couldn't verify nonce
shuffle-backend     | 2022/11/18 18:54:49 http: superfluous response.WriteHeader call from github.com/shuffle/shuffle-shared.HandleOpenId (shared.go:12981)```

Our .env contains:
SSO_REDIRECT_URL=https://shuffler.example.com

**Comment by frikky** [comment]
> I think we're still running into the same issue.
> 
> Process: Click SSO, redirects to Azure AD, sign in, Redirects to frontend on /api/v1/login_openid with below error: {"success": false, "reason": "Bad ID token provided"}
> 
> ```
>  Shuffle]$ sudo docker compose images
> Container            Repository                         Tag                 Image Id            Size
> shuffle-backend      ghcr.io/shuffle/shuffle-backend    1.1.0               fe6a8f517969        54.1MB
> shuffle-frontend     ghcr.io/shuffle/shuffle-frontend   1.1.0               df880c8858e5        190MB
> shuffle-opensearch   opensearchproject/opensearch       1.2.4               6842d435e62e        827MB
> ```
> 
> Redacted (example.com = internal domain) logs
> 
> ```
> shuffle-backend     | 2022/11/18 18:54:09 [WARNING] Api authentication failed in handleInfo: Missing authentication
> shuffle-backend     | 2022/11/18 18:54:09 [INFO] INITIAL Api authentication failed in notification list: Missing authentication
> shuffle-backend     | 2022/11/18 18:54:09 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
> shuffle-backend     | 2022/11/18 18:54:09 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
> shuffle-backend     | 2022/11/18 18:54:09 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
> shuffle-backend     | 2022/11/18 18:54:09 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
> shuffle-backend     | 2022/11/18 18:54:09 [INFO] INITIAL Api authentication failed in notification list: Missing authentication
> shuffle-backend     | 2022/11/18 18:54:09 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
> shuffle-backend     | 2022/11/18 18:54:09 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
> shuffle-backend     | 2022/11/18 18:54:09 [INFO] INITIAL Api authentication failed in notification list: Missing authentication
> shuffle-backend     | 2022/11/18 18:54:09 [WARNING] Api authentication failed in handleInfo: Missing authentication
> shuffle-backend     | 2022/11/18 18:54:10 URL: https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid
> shuffle-backend     | 2022/11/18 18:54:10 [DEBUG] Found OpenID url (client secret). Extra redirect check: /api/v1/checkusers - https://login.microsoftonline.com/be0003e8-****-****-****-************/oauth2/v2.0/authorize?client_id=294*****-****-****-****-*********b3c&response_type=id_token&scope=openid&redirect_uri=https%3A%2F%2Fshuffler.example.com%2Fapi%2Fv1%2Flogin_openid&state=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=&response_mode=form_post&nonce=b3JnPTFjY2I****REDACTED****dDbkszRnRYUm9hQjhhMGo=
> shuffle-backend     | 2022/11/18 18:54:49 eyJ0e***REDACTED****SSJ9
> shuffle-backend     | 2022/11/18 18:54:49 [WARNING] Couldn't find AUD - continuing to next: {"typ":"JWT","alg":"RS256","kid":"2ZQpJ3UpbjAYXYGaXEJl8lV0TOI"}
> shuffle-backend     | 2022/11/18 18:54:49 eyJh***REDACTED****iOiIyLjAifQ
> shuffle-backend     | 2022/11/18 18:54:49 [WARNING] Failed base64 decode of state (2): illegal base64 data at input byte 971
> shuffle-backend     | 2022/11/18 18:54:49 rk9Pb0***REDACTED****Pd2hw
> shuffle-backend     | 2022/11/18 18:54:49 [WARNING] Failed base64 decode of state (2): illegal base64 data at input byte 13
> shuffle-backend     | 2022/11/18 18:54:49 [ERROR] Bad ID token provided: Couldn't verify nonce
> shuffle-backend     | 2022/11/18 18:54:49 http: superfluous response.WriteHeader call from github.com/shuffle/shuffle-shared.HandleOpenId (shared.go:12981)```
> 
> Our .env contains:
> SSO_REDIRECT_URL=https://shuffler.example.com
> ```

Hey! The .env file is almost certainly the problem here. It needs to match the redirect URL you added to the app in Azure, as well as the URL in the .env file.

**Comment by bvirgilioamnh** [comment]
Hmmm I'm not sure if I understand. Our redirect URL is matching (.example.com is a find/replace with our internal domain which is set at Azure AD). It is the "public" frontend URL that we use to access Shuffle, which sits behind an Apache proxy.

This is what we have set for base_url and backend_hostname.

# Other configs
BASE_URL=https://192.168.142.5:5001
SSO_REDIRECT_URL=https://shuffler.example.com
BACKEND_HOSTNAME=192.168.142.5

**Comment by frikky** [comment]
Back from holiday finally!

Gotcha with the naming. Could you record the process when using SSO, or
could we set up a call to look at it? Unsure of this is a
missunderstanding, bad documentation or both.

Find my calendar available here: https://drift.me/frikky

**Comment by frikky** [comment]
Fixed a while back! Part of next release :)
