### ISSUE TITLE
Executions queue too big Shuffle stops working

### ISSUE THREAD

**Issue by Geronaso** [Shuffle/Shuffle#894]
Hi guys,

I have a pretty big environment and there were a lot of executions on queue, and I do not want to wait to everything to resolve, I want to clean the queue because when I try to create new workflows I can not test them, they are stuck at "EXECUTING" loop.

I have tried restarting the docker, but the queue was still there. I have tried to delete the workflow, but still whenever I try to test a workflow it is still stuck at the executing loop.

So is there any way to free the execution queue from Shuffle? I am out of ideas what might be the error here.

Edit:
I have also another question, I have Shuffle installed in a different environment, but whenever I send data to a webhook onprem I get the error {"success": false, "reason": "Workflow has no executing org defined"}. Any leads what this might be?

**Comment by azgaviperr** [comment]
Hello, do you run it in swarm mode?

**Comment by Geronaso** [comment]
No I do not, I read that it is recommended but I am not sure how to configure it.

**Comment by frikky** [comment]
Heyo! For the first issue; this is a typical issue when you start scaling up a bit. The easy option is to set up more servers with more orborus's and map them to new environments. To clean up the workflow queue, there's a button added to the "environments" part of the admin page. Jobs are otherwise saved both as jobs related to the workflow and executions under the "workflowexecution" and "workflowqueue-ENV" indexs that you can see here: https://shuffler.io/docs/configuration#database. Deleting these will give you more space and clear it all out.

As @azgaviperr mentioned however, swarm mode is the way to go. Scaling is the specific part that we provide professional support for - reach out to me at frikky@shuffler.io if you want to hear more about what we do!

As for the last part with webhooks: that's very strange! Are you on the 1.0.0/launch version?

**Comment by Geronaso** [comment]
Thanks for the answer frikky,

I have tried to clean the workflow queue by using the button in the admin page, but it did not work. For the database it is set as the default folder, ./shuffle-database. I am sorry but I am not very knowledgeable with databases. I do not see any db files in there, I only see a nodes folder which I think it is referenced to the orboros node(?) that is running the jobs. Could you give some guidelines how I can delete these indexes?

As for the second problem, I think it was the docker image, I have deleted it, re-downloaded and it worked.

I need to do some more testing, but if Shuffle meets our needs we might need to escalate it and I will reach out to you.

**Comment by frikky** [comment]
> Thanks for the answer frikky,
> 
> I have tried to clean the workflow queue by using the button in the admin page, but it did not work. For the database it is set as the default folder, ./shuffle-database. I am sorry but I am not very knowledgeable with databases. I do not see any db files in there, I only see a nodes folder which I think it is referenced to the orboros node(?) that is running the jobs. Could you give some guidelines how I can delete these indexes?
> 
> As for the second problem, I think it was the docker image, I have deleted it, re-downloaded and it worked.
> 
> I need to do some more testing, but if Shuffle meets our needs we might need to escalate it and I will reach out to you.

Np - just tell us if you want to get help during evaluation, as we do that for free to make sure you can get the most possible out of Shuffle.

As to the issue, we have lots of docs about database troubleshooting in https://shuffler.io/docs/troubleshooting

For this specific case, running these commands should work to delete the clogging if the opensearch port is open:

**Comment by Geronaso** [comment]
Hi frikky,

I tried to run the following command but I get an "Empty reply from server" message.

I tried to run the python script of the troubleshooting page, and it did work and stopped the executions that were pending, but when I generate a new alert in the webhook it still hangs in the executing loop.

**Comment by frikky** [comment]
> Hi frikky,
> 
> I tried to run the following command but I get an "Empty reply from server" message.
> 
> I tried to run the python script of the troubleshooting page, and it did work and stopped the executions that were pending, but when I generate a new alert in the webhook it still hangs in the executing loop.

Glad to hear the cleanup script worked at least. Please also restart Shuffle, as there is a large part probably saved in Cache.

Could you share the last logs in Orborus (docker logs shuffle-orborus) as well? I'm guessing it's struggling picking up jobs or something.

**Comment by Geronaso** [comment]
> 

Yes, is this the one?

> 2022/07/04 19:21:03 [WARNING] RUNNING_MODE not set - defaulting to Docker (NOT Kubernetes).
2022/07/04 19:21:03 [DEBUG] Set containerId network to dd6c6895f9d884a339ff8e2b3ac199fb6dc53c1c9af8abca2169759115f5aeab
2022/07/04 19:21:03 [INFO] Started with containerId "dd6c6895f9d884a339ff8e2b3ac199fb6dc53c1c9af8abca2169759115f5aeab"
2022/07/04 19:21:03 [INFO] Setting up execution environment
2022/07/04 19:21:03 [INFO] Running with timezone Europe/Amsterdam
2022/07/04 19:21:03 [DEBUG] Running docker with default socket /var/run/docker.sock
2022/07/04 19:21:03 [INFO] Looking for old containers (zombies)
2022/07/04 19:21:12 [INFO] Baseimage: frikky, Workertimeout: 600
2022/07/04 19:21:12 [INFO] Should STOP 0 containers.
2022/07/04 19:21:12 [INFO] Should REMOVE 16988 containers.


I see that there is a lot of containers I didn't notice, is this normal for shuffle? I have listed and they are all shuffle related

**Comment by frikky** [comment]
> > 
> 
> Yes, is this the one?
> 
> > 2022/07/04 19:21:03 [WARNING] RUNNING_MODE not set - defaulting to Docker (NOT Kubernetes).
> > 2022/07/04 19:21:03 [DEBUG] Set containerId network to dd6c6895f9d884a339ff8e2b3ac199fb6dc53c1c9af8abca2169759115f5aeab
> > 2022/07/04 19:21:03 [INFO] Started with containerId "dd6c6895f9d884a339ff8e2b3ac199fb6dc53c1c9af8abca2169759115f5aeab"
> > 2022/07/04 19:21:03 [INFO] Setting up execution environment
> > 2022/07/04 19:21:03 [INFO] Running with timezone Europe/Amsterdam
> > 2022/07/04 19:21:03 [DEBUG] Running docker with default socket /var/run/docker.sock
> > 2022/07/04 19:21:03 [INFO] Looking for old containers (zombies)
> > 2022/07/04 19:21:12 [INFO] Baseimage: frikky, Workertimeout: 600
> > 2022/07/04 19:21:12 [INFO] Should STOP 0 containers.
> > 2022/07/04 19:21:12 [INFO] Should REMOVE 16988 containers.
> 
> I see that there is a lot of containers I didn't notice, is this normal for shuffle? I have listed and they are all shuffle related

Yep. The default version of Shuffle deploys a new container for each app, leading to large amounts. This is largely why we recommend everyone going to swarm long-term, as the systems for that are built differently, not deploying so many containers. They do however take some setup.

Id recommend this:
1. Stop Shuffle (docker-compose down)
2. Remove all the containers (`docker rm $(docker ps -aq) --force`)
3. Restart Shuffle (docker-compose up -d)

Also have a look at our configuration docs, as the "default" settings are built for accessibility and testing, not production: https://shuffler.io/docs/configuration#production_readiness

**Comment by Geronaso** [comment]
> > > 
> > 
> > 
> > Yes, is this the one?
> > > 2022/07/04 19:21:03 [WARNING] RUNNING_MODE not set - defaulting to Docker (NOT Kubernetes).
> > > 2022/07/04 19:21:03 [DEBUG] Set containerId network to dd6c6895f9d884a339ff8e2b3ac199fb6dc53c1c9af8abca2169759115f5aeab
> > > 2022/07/04 19:21:03 [INFO] Started with containerId "dd6c6895f9d884a339ff8e2b3ac199fb6dc53c1c9af8abca2169759115f5aeab"
> > > 2022/07/04 19:21:03 [INFO] Setting up execution environment
> > > 2022/07/04 19:21:03 [INFO] Running with timezone Europe/Amsterdam
> > > 2022/07/04 19:21:03 [DEBUG] Running docker with default socket /var/run/docker.sock
> > > 2022/07/04 19:21:03 [INFO] Looking for old containers (zombies)
> > > 2022/07/04 19:21:12 [INFO] Baseimage: frikky, Workertimeout: 600
> > > 2022/07/04 19:21:12 [INFO] Should STOP 0 containers.
> > > 2022/07/04 19:21:12 [INFO] Should REMOVE 16988 containers.
> > 
> > 
> > I see that there is a lot of containers I didn't notice, is this normal for shuffle? I have listed and they are all shuffle related
> 
> Yep. The default version of Shuffle deploys a new container for each app, leading to large amounts. This is largely why we recommend everyone going to swarm long-term, as the systems for that are built differently, not deploying so many containers. They do however take some setup.
> 
> Id recommend this:
> 
>     1. Stop Shuffle (docker-compose down)
> 
>     2. Remove all the containers (`docker rm $(docker ps -aq) --force`)
> 
>     3. Restart Shuffle (docker-compose up -d)
> 
> 
> Also have a look at our configuration docs, as the "default" settings are built for accessibility and testing, not production: https://shuffler.io/docs/configuration#production_readiness

Thank you, it worked! 

I will read carefully the configuration docs as well, thanks again for the support.
