### ISSUE TITLE
Triggers don't start connected node

### ISSUE THREAD

**Issue by pandvan** [Shuffle/Shuffle#897]
**Describe the bug**
When a workflow is executed by a trigger, it always starts from the "starting node", even if the trigger node is pointing to another node.

**To Reproduce**
Create a workflow with 2 triggers.
Connect each one with 2 distinct nodes, set one of them as the starting node.
Check that the workflow will always begin from the starting node.

**Expected behavior**
As pointed by @frikky on Discord, triggers should start the node they are pointing to.

**Screenshots**
Example workflow to test the bug
<img src="https://user-images.githubusercontent.com/22728755/177157461-391f9850-f8be-48ae-b680-a6826abda4d3.png" width="250">

The issue was spotted both on a cloud and on a premise instance

**Comment by frikky** [comment]
This should be fixed in 1.1
