### ISSUE TITLE
Icons disappeared from Apps page

### ISSUE THREAD

**Issue by pandvan** [Shuffle/Shuffle#901]
**Describe the bug**
Using the frontend version 1.0.4 in an on-prem instance the 2 icons ("_Reload apps locally_" and "_Download from Github_") on the top-right corner of  _Apps_ page have been disappeared.

**To Reproduce**
Open Apps page.

**Expected behavior**
See the 2 icons

<img width="536" alt="image" src="https://user-images.githubusercontent.com/22728755/178920081-e0342121-7fad-4499-80d6-9fea4fc76ab0.png">

**Screenshots**
Same page but using versione 1.0.4 of shuffle-frontend

<img width="536" alt="image" src="https://user-images.githubusercontent.com/22728755/178920143-6d7513ce-1b37-464c-9d25-edf34a37c684.png">

**Comment by frikky** [comment]
Thanks! That's super weird, and if I remember correctly, only happened when you didn't have admin rights. 

What are your roles, just to make sure?

**Comment by pandvan** [comment]
> What are your roles, just to make sure?

The one and the only admin of the Shuffle instance

**Comment by frikky** [comment]
Gotcha, thanks!

**Comment by frikky** [comment]
This has been fixed in 1.1
