### ISSUE TITLE
GMail Trigger Issue while Authenticating from google

### ISSUE THREAD

**Issue by Arunankayu** [Shuffle/Shuffle#922]
Unable to Authenticate With Google OAuth 2.0. It give following error:

Authorization Error
Error 400: **redirect_uri_mismatch**

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.

![image](https://user-images.githubusercontent.com/42445982/186154737-fa9d555e-0e40-449f-9afb-c45ed3945cb1.png)

**Comment by frikky** [comment]
This was due to the URL being www.shuffler.io instead of shuffler.io I think. Added Redirect entry 

Could you try it on https://shuffler.io directly @Arunankayu ?

**Comment by frikky** [comment]
This has been fixed in October 2022
