### ISSUE TITLE
Problem parsing CSV to JSON in liquid

### ISSUE THREAD

**Issue by DavidtheGoliath** [Shuffle/Shuffle#924]
Some of data gets parsed and some do not get parsed and we get back unparsed data. From the liquid function below

```  

 {{ .csv_string | csv_parse | as_object }}

```

See below 
![csv to json](https://user-images.githubusercontent.com/31187099/186637049-e67bb252-3d99-42a0-9f97-a9def4bcc21e.png)

**Comment by frikky** [comment]
You got some sample data that doesn't work? It worked in my tests (:

Thanks

**Comment by DavidtheGoliath** [comment]
Here's the sample data I used for testing: [Servicepil.csv](https://github.com/Shuffle/Shuffle/files/9430359/Servicepil.csv)

**Comment by frikky** [comment]
This was fixed in 1.1 with the new SDK that uses new version of Liquidpy
