### ISSUE TITLE
Condition still displaying in the branch even though it has been deleted.

### ISSUE THREAD

**Issue by m1nk-code** [Shuffle/Shuffle#928]
If you put a condition in a branch between two nodes in a workflow, then delete it, it still shows like there's a condition in the branch. 

Steps to reproduce:
1. Start a new workflow
2. Put two nodes in it
3. Connect them and set a condition in the branch
4. Delete the condition
5. The workflow still shows that there is a condition

![image](https://user-images.githubusercontent.com/58112539/188013396-0fe0f545-005a-4679-bba9-aa363e12374c.png)

**Comment by frikky** [comment]
This is a visual bug and is fixed on refresh

**Comment by frikky** [comment]
Fixed
