### ISSUE TITLE
Workflow stuck at execution state

### ISSUE THREAD

**Issue by descof** [Shuffle/Shuffle#938]
**Describe the bug**
We are trying to run workflow on cloud environment. We were able to execute several tasks but since I added an outlook task, the execution keeps loading and the outlook task is not executed.
I tried to run the send mail taks in a dedicated workflow and it works successfully, but when I add to an existing workflow, the workflow never ends..

**Expected behavior**
Workflow end with the execution of all tasks

**Screenshots**
![image](https://user-images.githubusercontent.com/44446676/192218700-bc26fae6-3482-41b8-9764-1ea64beff5ef.png)

**Comment by frikky** [comment]
Pushed a fix to the cloud to default to the Cloud environment
