### ISSUE TITLE
User input trigger mail

### ISSUE THREAD

**Issue by Chicais** [Shuffle/Shuffle#945]
It would be nice if we could customize a little more the emails sent by the user input trigger.
Right now we can only add a text to the mail body.
On top of that would it be possible to give more options than just yes/no answers.

**Comment by frikky** [comment]
Thanks! These are indeed good ideas, but our ideas are grander - leaning towards 100% user control of what actually happens. No ETA, but totally get the point here

**Comment by frikky** [comment]
Continuation in #444
