### ISSUE TITLE
[BUG] List in forms

### ISSUE THREAD

**Issue by azgaviperr** [Shuffle/Shuffle#963]
There is an issue passing list into apps fields. but sending the fuill payload withouth the "automatically fix body" Option works . 
![image](https://user-images.githubusercontent.com/7451354/196369860-3713bc7d-d3a4-495c-a690-1844065fd1ce.png)

**Comment by frikky** [comment]
This has been fixed. It won't do escapes if it looks like the data inputted is JSON.
