### ISSUE TITLE
Add admin UI with an API to explore cache keys for an organization

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#968]

**Comment by frikky** [comment]
There is an index called "org_cache" that is being used. By listing out and sorting by the key "OrgId" or "org_id", we can get all the keys easily.

This should probably be added as a tab to a view called "/admin?tab=cache"

**Comment by frikky** [comment]
This requires an API for listing cache, and requires a frontend UI for exploring that same cache.

**Comment by frikky** [comment]
Additional info:
- Should look like the "Files" tab ish.
- Should be able to edit & delete keys
- Should be sorted by "edited" time

We will fix more on design in the future

**Comment by ayush0033** [comment]
@frikky yes we solved.
